### ISSUE TITLE
pip install tweety-ns does not install latest versions

### ISSUE THREAD

**Issue by rm0nroe** [mahrtayyab/tweety#10]
After installing with `pip install tweety-ns` and `pip3 install tweety-ns`, I am met with this error: 

```ModuleNotFoundError: No module named 'tweety.bot'; 'tweety' is not a package```

Please provide guidance. I am simply trying to run the below.

```
from tweety.bot import Twitter

app = Twitter("elonmusk")

all_tweets = app.get_tweets()
for tweet in all_tweets:
    print(tweet)

```

**Comment by rm0nroe** [comment]
My current python version is 3.10.5

**Comment by rm0nroe** [comment]
resolved - local setup issue. User error!

**Comment by jlerner** [comment]
What was the solution?

**Comment by jlerner** [comment]
Ah OK - you can't name the file `tweety.ns`.
