### ISSUE TITLE
Can I get the number of followers and followings of someone without logging in?

### ISSUE THREAD

**Issue by hello-eternity** [mahrtayyab/tweety#103]
I see that there seems to be no library that can correctly run this function.

**Comment by mahrtayyab** [comment]
Without logging in?

**Comment by hello-eternity** [comment]
if possible, but logging in is acceptable. but I didn't find the request method.

**Comment by hello-eternity** [comment]
I mean logging in twitter.

**Comment by mahrtayyab** [comment]
Try updating uisng pip install https://github.com/mahrtayyab/tweety/archive/main.zip --upgrade 
and use `get_user_followings` and `get_user_followers`

**Comment by hello-eternity** [comment]
hello, I try this method first login and use this code:
```
all_followers = app.get_user_followers("elonmusk")
print(all_followers)
```
but the reply is `UserFollowers(user_id=44196397, count=70)` it's not a right number, can you please check this?

**Comment by mahrtayyab** [comment]
Just like other `BaseGeneratorClass` child classes , you can `iter` over this `UserFollowings` and `UserFollowers` classes which will return `User`. You can also specify the number `pages` along with username.

**Comment by hello-eternity** [comment]
Thank you very much for your answer, but I actually want to get the quantity. If I use iter, it feels too slow. Is there a direct counting function?

**Comment by mahrtayyab** [comment]
If you want to get only follower count then you can use `get_user_info` which will return `User` object , `User` object has `followers_count` attribute.
