### ISSUE TITLE
`search` and `iter_search` methods throw `UnknownError`

### ISSUE THREAD

**Issue by pilot-to-sky** [mahrtayyab/tweety#104]
### Issue Description

I'm encountering an `UnknownError` when using the `search` and `iter_search` methods of the `Twitter` class in the `tweety` package. The error occurs when I try to fetch tweets related to a specific keyword.

#### Code to Reproduce

The following code blocks cause the issue:

```python
# Using search
tweets = app.search('premierleague', pages=100, filter_=SearchFilters.Latest())
```

```python
# Using iter_search
for search_obj, tweets in app.iter_search('elonmusk'):
    print(tweets)
```

#### Error Message

Here is the error traceback:

```
UnknownError: Unknown Error Occurs on Twitter
```

#### Environment

- Python version: 3.11
- Tweety version: 0.9.9.8
- OS: Debian 12.1

#### Additional Context

The error occurs only when using `search` and `iter_search`. Other methods like `get_tweets` seem to work fine.

**Comment by mahrtayyab** [comment]
@pilot-to-sky  are you logged in?

**Comment by mahrtayyab** [comment]
Issue will be closed in 3 days
