### ISSUE TITLE
How to bypass Rate limit exceeded for `SearchFilters.Latest()`

### ISSUE THREAD

**Issue by L300K** [mahrtayyab/tweety#105]
### How to bypass Rate limit exceeded?

when I use while true to loop `SearchFilters.Latest()`, it works for 20–30 requests. After that, it gets an error.
P.S. I'm logged in using session

Error Code : `tweety.exceptions_.UnknownError: Unknown Error Occurs on Twitter`

![image](https://github.com/mahrtayyab/tweety/assets/93990763/661856af-d6c0-4ea1-96ac-3aac383a7ac0)

**Comment by dgw** [comment]
Like every other time someone's asked what to do when Twitter limits them:

**Make requests less often.**

**Comment by L300K** [comment]
> Like every other time someone's asked what to do when Twitter limits them:
> 
> **Make requests less often.**
> 
> Like, you know it's a rate limit. The way to stop hitting a rate limit is to limit your rate so it stays under the cap.

Thank you for responding
There's no way to bypass it, right?

**Comment by dgw** [comment]
> There's no way to bypass it, right?

It's a server-side limit, not something the library is doing. Best you could do is parallelize your workload to multiple processes logged in as different accounts (possibly even on different IPs depending on how hard Twitter's limiting you).

But no, you're not going to bypass this just by tweaking a few lines of your current script.
