### ISSUE TITLE
How to solve this error! 

### ISSUE THREAD

**Issue by abdelkareemkobo** [mahrtayyab/tweety#107]
![image](https://github.com/mahrtayyab/tweety/assets/72500236/e462e484-6244-473a-97e3-9028861d10a6)

**Comment by mahrtayyab** [comment]
Delete tw_session file in the directory

**Comment by abdelkareemkobo** [comment]
@mahrtayyab it's working now but i have another error when i search for non-english words like arabic word " رجل" i get the folloiwng error words = u"الاختلاط"
print(words)
len(words)
tweets = app.search(words, pages=1)
x = 0
for tweet in tweets:
    x += 1
    # Print the tweet after encoding to UTF-8
    # print(tweet.encode('utf-8'))  # Ensure proper encoding for display

print(x)
print(len(tweets))
File "/httpx/_utils.py", line 52, in normalize_header_value
    return value.encode(encoding or "ascii")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 29-36: ordinal not in range(128)

**Comment by mahrtayyab** [comment]
#108
