### ISSUE TITLE
How to solve the problem of searching for non-english words  like arabic 

### ISSUE THREAD

**Issue by abdelkareemkobo** [mahrtayyab/tweety#108]
when i search for non-english words like arabic word " رجل" i get the folloiwng error words = u"الاختلاط"
print(words)
len(words)
tweets = app.search(words, pages=1)
x = 0
for tweet in tweets:
x += 1
# Print the tweet after encoding to UTF-8
# print(tweet.encode('utf-8')) # Ensure proper encoding for display

print(x)
print(len(tweets))
File "/httpx/_utils.py", line 52, in normalize_header_value
return value.encode(encoding or "ascii")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 29-36: ordinal not in range(128)

**Comment by mahrtayyab** [comment]
try using after updating with source

**Comment by abdelkareemkobo** [comment]
@mahrtayyab Thanks it is working now but i get  another error 
![image](https://github.com/mahrtayyab/tweety/assets/72500236/b2f8be14-7c92-444b-93d7-e10007836f81)

**Comment by mahrtayyab** [comment]
Slow down your requests

**Comment by mahrtayyab** [comment]
it should be `tweet.author.location`
