### ISSUE TITLE
get_tweets get wrong number tweets

### ISSUE THREAD

**Issue by fishmisswater** [mahrtayyab/tweety#109]
my code：
`all_tweets = app.get_tweets(target_name,pages=1,wait_time=12)`
the real tweets number is 49，but only get 20

**Comment by dgw** [comment]
You're restricting it to one page…

**Comment by fishmisswater** [comment]
yes，some person 1 page 100 tweets，some 1 page 20 tweets，It's puzzling

**Comment by mahrtayyab** [comment]
if you care comfortable can send the username of both users?

**Comment by mahrtayyab** [comment]
issue begin closed due to inactivity
