### ISSUE TITLE
Cannot directly fetch details of a reply?

### ISSUE THREAD

**Issue by dgw** [mahrtayyab/tweety#11]
I am trying to use Tweety for an update to https://github.com/sopel-irc/sopel-twitter and have run into an issue. Passing the ID of a reply to `tweet_detail()` returns data about the tweet _it's replying to_. Further, the tweet ID passed in does not appear in the `comments` field either, so I can't get to its details from there:

```pycon
>>> tweet = client.tweet_detail('1622759716798750721')
>>> tweet.id
'1622759147400794112'
>>> [t.id for t in tweet.comments]
['1622759938714923008', '1622824165966503937']
```

It seems that `tweet.id`, `tweet.author` and `tweet.text` (for example) are replaced by the parent tweet's info, but the `tweet.comments` list replies to the original ID, _not_ the parent—which means that for `tweet.id` *112 above, the `comments` listed are actually replies to `tweet.id` *721.

This is confusing. Is it working as designed? If so I'll need a bit of advice to address this use case (or to find another library).

**Comment by mahrtayyab** [comment]
Yes , this is a known issue to me , working on it , replied_to will be added in few days , + many other fixes.

**Comment by dgw** [comment]
Not to pressure you or anything, but bugs like this just got a lot more important because of:

![image](https://user-images.githubusercontent.com/164140/228702505-7fc6105c-ef04-4747-8684-5d7c275d0ff0.png)

**Comment by mahrtayyab** [comment]
You can try pulling new update and check , feel free to open the issue if anything happens
