### ISSUE TITLE
Searching a Keyword

### ISSUE THREAD

**Issue by bigleeth** [mahrtayyab/tweety#112]
Hi, I am working on acquiring #starbucks mentioned posts while the syntax does not work properly.

Do you have an idea to fix the script below?

Meanwhile, I have found Get Tweet, which is applied  with 'app.get_tweets' instead of  'app.search', functions correctly.

```
  from tweety import Twitter
  
  app = Twitter("session")
  
  all_tweets = app.search("starbucks")
  for tweet in all_tweets:
      print(tweet.date)
      print(tweet.id)
      print(tweet.author)
      print(tweet.text)
      print(tweet.views)

```

Many thanks.

**Comment by mahrtayyab** [comment]
Are you logged in?

**Comment by bigleeth** [comment]
> Are you logged in?

Oh yes! I am on now.

**Comment by bigleeth** [comment]
> > Are you logged in?
> 
> Oh yes! I am in now on a same web browser.

It shows response as follows. (I modified User id, username, name)

`User(id=1716833560321177123, username=2_tae1222132yun, name=Tssaa2e, verified=False)
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
Cell In[40], line 7
      4 app.start()
      5 print(app.user)
----> 7 all_tweets = app.search("starbucks")
      8 for tweet in all_tweets:
      9     print(tweet.date)

File ~\anaconda3\Lib\site-packages\tweety\bot.py:178, in BotMethods.search(self, keyword, pages, filter_, wait_time, cursor)
    174     wait_time = 0
    176 search = Search(keyword, self, pages, filter_, wait_time, cursor)
--> 178 list(search.generator())
    180 return search

File ~\anaconda3\Lib\site-packages\tweety\types\base.py:46, in BaseGeneratorClass.generator(self)
     44 def generator(self):
     45     for page in range(1, int(self.pages) + 1):
---> 46         results = self.get_next_page()
     48         yield self, results
     50         if not self.is_next_page:

File ~\anaconda3\Lib\site-packages\tweety\types\search.py:37, in Search.get_next_page(self)
     35 def get_next_page(self):
     36     if self.is_next_page:
---> 37         response = self.client.http.perform_search(self.keyword, self.cursor, self.filter)
     38         thisTweets = self._parse_response(response)
     40         self['is_next_page'] = self.is_next_page

File ~\anaconda3\Lib\site-packages\tweety\http.py:139, in Request.perform_search(self, keyword, cursor, filter_)
    136 # del request_data['headers']['content-type']
    137 request_data['headers']['referer'] = f"https://twitter.com/search?q={keyword}"
--> 139 response = self.__get_response__(**request_data)
    140 return response

File ~\anaconda3\Lib\site-packages\tweety\http.py:72, in Request.__get_response__(self, return_raw, ignoreNoneData, **request_data)
     70 if response_json.get("errors"):
     71     error = response_json['errors'][0]
---> 72     return GenericError(
     73         response, error.get("code"), error.get("message")
     74     )
     76 if return_raw:
     77     return response

File ~\anaconda3\Lib\site-packages\tweety\types\n_types.py:65, in GenericError.__init__(self, response, error_code, message)
     63 self.message = message
     64 self.retry_after = self._get_retry_after()
---> 65 self._raise_exception()

File ~\anaconda3\Lib\site-packages\tweety\types\n_types.py:85, in GenericError._raise_exception(self)
     76 if self.EXCEPTIONS.get(self.error_code):
     77     raise self.EXCEPTIONS[self.error_code](
     78         error_code=self.error_code,
     79         error_name=TWITTER_ERRORS[self.error_code],
   (...)
     82         retry_after=self.retry_after
     83     )
---> 85 raise UnknownError(
     86     error_code=self.error_code,
     87     error_name=TWITTER_ERRORS[self.error_code],
     88     response=self.response,
     89     message="[{}] {}".format(self.error_code, self.message)
     90 )

UnknownError: [366] Query violation: Variable 'product' has an invalid value: Variable 'product' has coerced Null value for NonNull type 'SearchProductInput!'`

**Comment by mahrtayyab** [comment]
Upgrade to latest source

**Comment by bigleeth** [comment]
It works! many thanks :)
