### ISSUE TITLE
Error in docker container

### ISSUE THREAD

**Issue by stormshadowv** [mahrtayyab/tweety#115]
Hi. When I try to execute media.download(), I get httpx.ConnectError: [Errno 99] Cannot assign requested address. 

The error occurs only in the docker, if I run the script outside the docker, everything is fine

**Comment by mahrtayyab** [comment]
It happens on every media?

**Comment by stormshadowv** [comment]
No. It's downloading some media. But I just noticed that even outside of the docker, I can't download media either. 

httpx.ConnectTimeout: _ssl.c:990: The handshake operation timed out
or
httpcore.ConnectError: [Errno 101] Network is unreachable

**Comment by mahrtayyab** [comment]
can you post logs using logging module

**Comment by mahrtayyab** [comment]
update to latest source
