### ISSUE TITLE
`flow_name` or `flow_token` is missing

### ISSUE THREAD

**Issue by darknessest** [mahrtayyab/tweety#118]
After the recent updates the login stopped working for new sessions. I'm receiving the following error:

```
tweety.exceptions_.UnknownError: [357] Either flow_name or flow_token need to be defined
```

I looked a bit deeper and it seems like there's an issue with getting the `flow_token`. 
When [this line](https://github.com/mahrtayyab/tweety/blob/312984adb7ad330f59819fc0efd37d16c4da6982/src/tweety/auth.py#L146C13-L146C84) is executed the `_login_payload` has value `None` for whatever reason. I wasn't able to find out if something changes the value of the `_login_flow_state`, as this probably affects the empty payload.

**Comment by mahrtayyab** [comment]
can you please open auth.py and at line 148 add `print(self._last_json)` ,try logging in and send the logs here

**Comment by darknessest** [comment]
Sure, so apparently the `tweety.auth:_login` is called 3 times. For the following flow states: `LoginJsInstrumentationSubtask`, then `LoginEnterUserIdentifierSSO`, and the last one which isn't covered by tweety - `ArkoseLogin`. 

The value of the `self._last_json` after encountering the last flow state is: 
```json
{
    "flow_token": "g;169930709927769731:-1699307099492:8wnhHEn9GTHUQWE23H0EkP4y:4",
    "status": "success",
    "subtasks": [
        {
            "subtask_id": "ArkoseLogin",
            "subtask_back_navigation": "cancel_flow",
            "web_modal": {
                "url": "https://mobile.twitter.com/i/ocf_arkose_challenge?publicKey=arkose_challenge_login_web_prod",
                "style": "full_screen",
                "next_link": {
                    "link_type": "task",
                    "link_id": "next_link"
                },
                "fail_link": {
                    "link_type": "abort",
                    "link_id": "cancel_link"
                }
            }
        }
    ]
}
```

**Comment by mahrtayyab** [comment]
`ArkoseLogin` , there you go , we have a captcha.

**Comment by darknessest** [comment]
> `ArkoseLogin` , there you go , we have a captcha.


That's right, so what's the library's behavior should be? 
An unknown exception like it is now or perhaps a redirect to the captcha page or something else?

**Comment by mahrtayyab** [comment]
The whole objective of tweety was not to use browser , I have not encountered `ArkoseLogin` yet. I think I would implement both browser and non-browser solution , but it would require significant amount of time. You can use cookies or auth_token till then.
