### ISSUE TITLE
Can't search tweets

### ISSUE THREAD

**Issue by NeloBlivion** [mahrtayyab/tweety#12]
`app.search` seems to be broken.
Sample:
```py
from tweety.bot import Twitter
app = Twitter()
tweet = app.search("test")
```
Error:
```py
Traceback (most recent call last):
  File "<pyshell4>", line 1, in <module>
    a_tweet = app.search("test")
  File "C:\Python38\lib\site-packages\tweety\bot.py", line 169, in search
    return Search(keyword, self.request, pages, filter_, wait_time, cursor)
  File "C:\Python38\lib\site-packages\tweety\types\search.py", line 15, in __init__
    self._search(pages, wait_time)
  File "C:\Python38\lib\site-packages\tweety\types\search.py", line 90, in _search
    self.get_next_page()
  File "C:\Python38\lib\site-packages\tweety\types\search.py", line 25, in get_next_page
    self._parse_response(response)
  File "C:\Python38\lib\site-packages\tweety\types\search.py", line 41, in _parse_response
    users = response.json()['globalObjects']['users']
KeyError: 'globalObjects'
```

**Comment by mahrtayyab** [comment]
I can't really reproduce the issue , can you confirm now?

![image](https://user-images.githubusercontent.com/38404705/218370359-e7a8f0e2-0490-47a8-92fb-487d4eba2c63.png)

**Comment by NeloBlivion** [comment]
Hm no matter what I try it won't work, this is happening on two separate machines (both py3.10)

**Comment by mahrtayyab** [comment]
Is Twitter working for you on browser?

**Comment by NeloBlivion** [comment]
Well of course, it'd be pretty odd if it wasn't. User tweets work fine but search breaks, this happens both on my local machine and a remote server I installed it on.

**Comment by mahrtayyab** [comment]
I am unable to reproduce the error , can you please take time and do the following ,
Inside module files , edit http.py file and at line 88 , add `print(response)` , then try and send the output here

**Comment by NeloBlivion** [comment]
Getting a 404 error
`response.text` returns `{"errors":[{"message":"Sorry, that page does not exist","code":34}]}`
Haven't modified anything though 🤷 
```py
        self.__search_url = "https://twitter.com/i/api/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&q={}&count=20&query_source=typeahead_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel%2CvoiceInfo"
```

**Comment by hubmos** [comment]
Experienced the same error, "KeyError: 'globalObjects'". I was missing the package wget. After I installed wget it works again.

**Comment by NeloBlivion** [comment]
Unfortunately wget never changed anything for me

**Comment by EivindSundberg** [comment]
Hm, okay so I first did "pip install wget", but that did not help. I then did "mamba install wget". This installed many packages:

![image](https://user-images.githubusercontent.com/105429615/219369095-18d1fe33-19c4-4759-bc3b-30333dfdfe98.png)

It also upgraded loads of packages. After that search worked, so my guess is that there was some dependency-package that needed to be upgraded or installed maybe?

**Comment by vimal-quilt** [comment]
Hi 
thanks for the wonderful library. i am receiving the same error as others highlighted. i am using the latest version in my mac pc. (0.5.1). Kindly support.

> Getting a 404 error

**Comment by DrSocket** [comment]
hello, same here, error when doing search, wget is installed: 
    users = response.json()['globalObjects']['users']
            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'globalObjects'

**Comment by mahrtayyab** [comment]
Okay I have found the Problem , it looks like Twitter is pushing everything over HTTP/2 while Requests only support HTTP/1.1 , I will be pushing an update later today after further testing

**Comment by madhukar01** [comment]
What is the solution for this?
I am facing the same issue since yesterday (it was working fine before).
I am guessing twitter changed something again?

**Comment by mahrtayyab** [comment]
> What is the solution for this? I am facing the same issue since yesterday (it was working fine before). I am guessing twitter changed something again?

Yes ,Now you can't search without Logging in , working on implementing cookies.

**Comment by madhukar01** [comment]
> Yes ,Now you can't search without Logging in , working on implementing cookies.

I guessed so. I temporarily updated the http.py to include cookies and been using it since then.

**Comment by mahrtayyab** [comment]
Cookies implementation is done, do upgrade and **please** check full documentation **important**.

**Comment by EsqerYasen** [comment]
@mahrtayyab 
`class X:
    def __init__(self):
        proxy_info = config_reader.get_proxy_config()
        proxy = Proxy(
            host=proxy_info["host"], port=proxy_info["port"], proxy_type=PROXY_TYPE_HTTP
        )
        twitter_account = config_reader.get_twitter_account()
        # use session file to login if exists
        session_file = "session.tw_session"
        if os.path.exists(session_file):
            self.app = Twitter("session", proxy=proxy)
            self.app.connect()
            logging.info("X connected from session file")
        else:
            self.app = Twitter("session", proxy=proxy)
            self.app.sign_in(twitter_account["username"], twitter_account["password"])
            self.app.connect()
            logging.info("X connected from username and password")`
this is the code , als has same error : [34] Sorry, that page does not exist

**Comment by EsqerYasen** [comment]
> @mahrtayyab
> 
> ```python
> class X:
>     def __init__(self):
>         proxy_info = config_reader.get_proxy_config()
>         proxy = Proxy(
>             host=proxy_info["host"], port=proxy_info["port"], proxy_type=PROXY_TYPE_HTTP
>         )
>         twitter_account = config_reader.get_twitter_account()
>         # use session file to login if exists
>         session_file = "session.tw_session"
>         if os.path.exists(session_file):
>             self.app = Twitter("session", proxy=proxy)
>             self.app.connect()
>             logging.info("X connected from session file")
>         else:
>             self.app = Twitter("session", proxy=proxy)
>             self.app.sign_in(twitter_account["username"], twitter_account["password"])
>             self.app.connect()
>             logging.info("X connected from username and password")
> ```
> 
> this is the code , als has same error : [34] Sorry, that page does not exist

is this because rate limit?
