### ISSUE TITLE
Hide sensitive content filter

### ISSUE THREAD

**Issue by buckydroid** [mahrtayyab/tweety#120]
Is there anyways to show sensitive content while searching for tweets,
<img width="293" alt="Screenshot 2023-11-04 172235" src="https://github.com/mahrtayyab/tweety/assets/17883122/7d094731-4f3e-4b2f-8af3-d6b8ed7d62c5">

tweets = app.search("query", filter_=SearchFilters.Latest())

For some reasons most of my normal queries are getting hidden in sensitve content category. So is it possible to do that using this library right now.

**Comment by mahrtayyab** [comment]
we need to separately set `searchSafety` settings which is not currently added, `Hide sensitive content` is by default disabled.
