### ISSUE TITLE
KeyError: 'guest_token'

### ISSUE THREAD

**Issue by Burlin-star** [mahrtayyab/tweety#121]
Traceback (most recent call last):
  File "twitter.py", line 3, in <module>
    twitterServer = Twitter("session")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tweety/bot.py", line 34, in __init__
    self.request = self.http = Request(max_retries=10, proxy=self._proxy)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tweety/http.py", line 20, in __init__
    self.__guest_token = self._get_guest_token(max_retries)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tweety/http.py", line 64, in _get_guest_token
    token = self.__builder.guest_token = response['guest_token'] # noqa
KeyError: 'guest_token'

**Comment by mahrtayyab** [comment]
Upgrade to latest github source

**Comment by Burlin-star** [comment]
After running "pip install https://github.com/mahrtayyab/tweety/archive/main.zip --upgrade" , but my code still not work. this is the new error:

**Comment by mahrtayyab** [comment]
uninstall first and then install from source

**Comment by Burlin-star** [comment]
I tried "pip uninstall tweety-ns" and then "pip install https://github.com/mahrtayyab/tweety/archive/main.zip --upgrade", the error still exists.

**Comment by mahrtayyab** [comment]
can you please by any chance send your country name

**Comment by Burlin-star** [comment]
This code is running on my Amazon server. The server node is at Seoul.

**Comment by mahrtayyab** [comment]
![image](https://github.com/mahrtayyab/tweety/assets/38404705/e2b9a307-b388-4372-b28f-100018afd3d2)
Completing Fine on "Korea" proxy , do check if twitter service is accessible from node.

**Comment by Burlin-star** [comment]
The problem is in Twitter not sending a token to any AWS IP, need add a proxy for request.
