### ISSUE TITLE
Add option to upload media with already existing media_id

### ISSUE THREAD

**Issue by kairusds** [mahrtayyab/tweety#123]
Hello, is it possible to stop the library from uploading a file and to just directly pass an existing media's ID for the file?

**Comment by mahrtayyab** [comment]
You can have use some hacky approach like

``` python

from tweety.types import UploadedMedia

#assuming client is your authenticated Twitter class instance

media = UploadedMedia(None, client)
media.media_id = "your media id"
client.create.tweet("text", files=media)

```

**Comment by kairusds** [comment]
> You can have use some hacky approach like
> 
> ```python
> from tweety.types import UploadedMedia
> 
> #assuming client is your authenticated Twitter class instance
> 
> media = UploadedMedia(None, client)
> media.media_id = "your media id"
> client.create_tweet("text", files=media)
> ```

thank you

**Comment by kairusds** [comment]
> You can have use some hacky approach like
> 
> ```python
> from tweety.types import UploadedMedia
> 
> #assuming client is your authenticated Twitter class instance
> 
> media = UploadedMedia(None, client)
> media.media_id = "your media id"
> client.create_tweet("text", files=media)
> ```

Hmm, that doesnt work:
```
File "/usr/local/lib/python3.10/dist-packages/tweety/types/n_types.py", line 149, in __init__
    self.size = self._get_size()
  File "/usr/local/lib/python3.10/dist-packages/tweety/types/n_types.py", line 160, in _get_size
    return os.path.getsize(self._file)
  File "/usr/lib/python3.10/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

But this is what I'm using at the moment which directly accesses the internal request property to send out a tweet with the media_id:
```
from tweety.types import UploadedMedia, Tweet

media_params = dict(
	file_path="dummyfile",
	client=None,
	media_category="tweet_video"
)
file = UploadedMedia(**media_params)
file.media_id = "media id"

tweet_params = dict(
	text="test with already existing media",
	files=[file],
	filter_=None,
	reply_to=None,
	pool=None
)

response = app.request.create_tweet(**tweet_params)
response['data']['create_tweet']['tweet_results']['result']['__typename'] = "Tweet"
post = Tweet(response, app, response)
```

**Comment by kairusds** [comment]
> You can have use some hacky approach like
> 
> ```python
> from tweety.types import UploadedMedia
> 
> #assuming client is your authenticated Twitter class instance
> 
> media = UploadedMedia(None, client)
> media.media_id = "your media id"
> client.create_tweet("text", files=media)
> ```

Hmm, that doesnt work:
```
File "/usr/local/lib/python3.10/dist-packages/tweety/types/n_types.py", line 149, in __init__
    self.size = self._get_size()
  File "/usr/local/lib/python3.10/dist-packages/tweety/types/n_types.py", line 160, in _get_size
    return os.path.getsize(self._file)
  File "/usr/lib/python3.10/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

But this is what I'm using at the moment which directly accesses the internal request property to send out a tweet with the media_id:

```python
from tweety.types import UploadedMedia, Tweet

media_params = dict(
	file_path="dummyfile",
	client=None,
	media_category="tweet_video"
)
file = UploadedMedia(**media_params)
file.media_id = "media id"

tweet_params = dict(
	text="testing",
	files=[file],
	filter_=None,
	reply_to=None,
	pool=None
)

response = app.request.create_tweet(**tweet_params)
response['data']['create_tweet']['tweet_results']['result']['__typename'] = "Tweet"
post = Tweet(response, app, response)
```

**Comment by mahrtayyab** [comment]
Okay you can pass any valid file_path to `UploadedMedia` as placeholder

``` python
from tweety.types import UploadedMedia

#assuming client is your authenticated Twitter class instance

media = UploadedMedia(file_path, client)
media.media_id = "your media id"
client.create_tweet("text", files=media)

```

**Comment by kairusds** [comment]
> Okay you can pass any valid file_path to `UploadedMedia` as placeholder
> 
> ```python
> from tweety.types import UploadedMedia
> 
> #assuming client is your authenticated Twitter class instance
> 
> media = UploadedMedia(file_path, client)
> media.media_id = "your media id"
> client.create_tweet("text", files=media)
> ```

this works better than my current hacky solution ty
