### ISSUE TITLE
ImportError: cannot import name 'Twitter' from 'tweety.bot'

### ISSUE THREAD

**Issue by N1ght420** [mahrtayyab/tweety#125]
![Screenshot from 2023-11-18 12-34-08](https://github.com/mahrtayyab/tweety/assets/38994110/5694afa0-a0fd-4867-8e76-42a6c2ee59db)

![Screenshot from 2023-11-18 12-33-01](https://github.com/mahrtayyab/tweety/assets/38994110/e7f4b5ea-7316-40b9-9ebe-0a01d83cae12)

**Comment by mahrtayyab** [comment]
There was a API interface change in library 
``` python

from tweety import Twitter

client = Twitter('session')
client.start()
for search_obj, tweets in client.iter_search('elonmusk'):
    print(tweets)
```

Docs will be updated in next Pypi release.

**Comment by mahrtayyab** [comment]
The idea was originally to separated `.bot` and `.client` for both use cases , but after Twitter Changes , both were kind of merged.

**Comment by alonenettr** [comment]
Is it fixed in the new version?

**Comment by mahrtayyab** [comment]
> There was a API interface change in library
> 
> ```python
> from tweety import Twitter
> 
> client = Twitter('session')
> client.start()
> for search_obj, tweets in client.iter_search('elonmusk'):
>     print(tweets)
> ```
> 
> Docs will be updated in next Pypi release.

@alonenettr
