### ISSUE TITLE
Getting all tweets doesn't work

### ISSUE THREAD

**Issue by michalborkowski96** [mahrtayyab/tweety#128]
Hi.

I wrote a simple loop:

```
    def _get_all_user_tweets(self, user_id):
        user_tweets = tweety.types.UserTweets(user_id, self.tweety, get_replies=False)
        tweets = user_tweets.get_next_page()
        while len(tweets) > 0:
            yield from tweets
            tweets = user_tweets.get_next_page()
```

After some time I discovered that, no matter how many tweets there are, Tweety returns up to about 700 of them. I came across this thread:

https://github.com/JustAnotherArchivist/snscrape/issues/636

where they suggest that Twitter returns a bunch of empty pages and then starts returning tweets again.

I tried making a loop that, if given page has no tweets, calls `get_next_page()` up to 20 times, but every single of these calls was an empty page in my case.

I don't really know much about Twitter API, so I'm not sure how I could help, but in any case this is seems like a serious issue.

**Comment by mahrtayyab** [comment]
I didn't observed this behavior , if you are comfortable , send the username of the user.

**Comment by michalborkowski96** [comment]
I can reproduce this with any account really.

```
>>> t = tweety.Twitter("session")
>>> t.load_cookies(cookies) # my personal cookies
User(id=<redacted>, username=<redacted>, name=<redacted>, verified=False)
>>> user_tweets = tweety.types.UserTweets(t.get_user_info("bbc").id, t, get_replies=False)
>>> tweet_pages = []
>>> while len(tweet_pages) == 0 or len(tweet_pages[-1]) > 0:
...     tweet_pages.append(user_tweets.get_next_page())
...     print(len(tweet_pages))
...
1
<...>
44
>>> total_tweets = sum([len(tt) for tt in tweet_pages])
>>> total_tweets
848
```

The actual account `bbc` has more than 30k tweets.

```
$ pip freeze | grep tweety
tweety-ns==0.9.9.5
```

**Comment by mahrtayyab** [comment]
making that much requests without wait , rate limit is sure.

**Comment by michalborkowski96** [comment]
How do you differentiate rate limiting and end-of-tweets?

**Comment by yyounas1** [comment]
Hello. I am facing the same issue. No matter how long the waiting time is, it always gives me between 700-800 tweets. The issue persists even if I use cursors.

**Comment by pclavell** [comment]
In my case I am not getting more than 100 tweets per user and in many cases I can not even get 1 single tweet.

**Comment by mahrtayyab** [comment]
Yes Twitter has limit the userTweets to last 6 or 7 days now , there is no way to get beyond that now no matter how many cursors you try , use advance search for that.
