### ISSUE TITLE
feature request for api call of TweetResultByRestId

### ISSUE THREAD

**Issue by dohyung97022** [mahrtayyab/tweety#129]
First thanks for this awesome repo. 
I have been using this to scrape data, working out great!

Although testing today, I have tried tweet_detail and X seems to return a 400.
I am guessing they have changed the api if I am not mistaken.

So, I was checking out X what api they request.
https://twitter.com/anyuser/status/1727888536680940019
![image](https://github.com/mahrtayyab/tweety/assets/67013169/bf2f3bad-9d0d-48cc-adde-60c74c60e661)

Replacing tweet_detail itself or adding a v2 seems sufficient enough.
The previous function has the purpose of getting detail of a single tweet.
```python
        def tweet_detail(self, identifier: str) -> Tweet:
        """
        Get Detail of a single tweet
        ...
        """
```

So I was thinking somthing like
bot.py
```python
    def tweet_detail_v2(self, identifier: str) -> Tweet:
        """
        Get Detail of a single tweet v2

        :param identifier: (`str`) The unique identifier of the tweet , either the `Tweet id` or `Tweet Link`

        :return: .types.twDataTypes.Tweet
        """

        tweetId = re.findall("\d+", identifier)[-1]
        response = self.request.det_tweet_detail_v2(tweetId)
        return Tweet(response, self, response)

```

http.py
```python
    def det_tweet_detail_v2(self, tweetId):
        response = self.__get_response__(**self.__builder.tweet_detail_v2(tweetId))
        return response
```

builder.py
```python
@return_with_headers
    def tweet_detail_v2(self, tweet_id):

        variables = {"tweetId": str(tweet_id), "withCommunity": False,
                     "includePromotedContent": True, "withVoice": False}

        features = {
            "creator_subscriptions_tweet_preview_api_enabled": True,
            "c9s_tweet_anatomy_moderator_badge_enabled": True,
            "tweetypie_unmention_optimization_enabled": True,
            "responsive_web_edit_tweet_api_enabled": True,
            "graphql_is_translatable_rweb_tweet_is_translatable_enabled": True,
            "view_counts_everywhere_api_enabled": True,
            "longform_notetweets_consumption_enabled": True,
            "responsive_web_twitter_article_tweet_consumption_enabled": False,
            "tweet_awards_web_tipping_enabled": False,
            "responsive_web_home_pinned_timelines_enabled": True,
            "freedom_of_speech_not_reach_fetch_enabled": True,
            "standardized_nudges_misinfo": True,
            "tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled": True,
            "longform_notetweets_rich_text_read_enabled": True,
            "longform_notetweets_inline_media_enabled": True,
            "responsive_web_graphql_exclude_directive_enabled": True,
            "verified_phone_label_enabled": False,
            "responsive_web_media_download_video_enabled": False,
            "responsive_web_graphql_skip_user_profile_image_extensions_enabled": False,
            "responsive_web_graphql_timeline_navigation_enabled": True,
            "responsive_web_enhance_cards_enabled": False
        }

        params = {'variables': str(json.dumps(variables)), 'features': str(json.dumps(features))}
        return "GET", self._build(self.URL_TWEET_DETAILS_V2, urlencode(params))
```

and add this to the to the urlBuilder
```python
URL_TWEET_DETAILS_V2 = "https://api.twitter.com/graphql/5GOHgZe-8U2j5sVHQzEm9A/TweetResultByRestId"
```

Sould I contribute?
Do you have any rules for merging?
Or can someone merge this? XD

I did check this out myself.
I does work, but I have no clue how you guys handle exceptions within.
Just to be safe.

**Comment by mahrtayyab** [comment]
`TweetRestByRestId` is used when the user is not logged in , so I will suggest some changes , instead by  `tweet_detail_v2` we can check either the user is logged in or not inside `tweet_detail` and then call `tweet_detail_v2` or `tweet_detail` in http.py based on previous result. I think it would be more cleaner.

**Comment by dohyung97022** [comment]
I am thinking
```URL_TWEET_DETAILS_AS_GUEST```
or
```URL_TWEET_DETAILS_WITHOUT_LOGIN```
what you think better?

also
Does URL_AUSER means that it is logged in?
Is that short for as user?
If that is so

maybe?
```URL_TWEET_DETAILS```
```URL_AUSER_TWEET_DETAILS```

**Comment by mahrtayyab** [comment]
if we create two public methods for doing same thing (getting tweet) , it wouldn't be good in term of user experience , keeping only one public method for getting tweet , user is logged in or not logged should be done by the library under the hood .

**Comment by dohyung97022** [comment]
I did use the same function of tweet_detail in bot.py
but did add as_guest function to http.py
If that was what you meant.

https://github.com/mahrtayyab/tweety/compare/main...dohyung97022:tweety:main

I could also separate by logged_in boolean in http.py like this.
```python
    def get_tweet_detail(self, tweetId, logged_in: bool = True, cursor=None):
        if logged_in:
            response = self.__get_response__(**self.__builder.tweet_detail(tweetId, cursor))
        else:
            response = self.__get_response__(**self.__builder.tweet_detail_as_guest(tweetId, cursor))
        return response
```

What would you prefer?

**Comment by mahrtayyab** [comment]
yes

**Comment by dohyung97022** [comment]
did create the pull request
https://github.com/mahrtayyab/tweety/pull/130/commits/c7883b241a039692d18e365fb7a06348950a037f

separated within with the existance of self.user in http.py get_tweet_detail as last mentioned.
