### ISSUE TITLE
Number of pages - get_tweets

### ISSUE THREAD

**Issue by AkimParis** [mahrtayyab/tweety#13]
Hello guys,

Thank you Mahrtayyab for the work.

I am trying to get_tweets for a public account on a one-year basis (until Feb 2022). Unfortunately, It doesn't go after October 2022...
I tried to modify the parameters "pages" and "wait time", but it only got 20 duplicates of the same tweet.

Does anyone get a limitation?

Thank you!

**Comment by mahrtayyab** [comment]
It is happening for other users too?

**Comment by cqsd** [comment]
How far back are you going? Twitter's frontend APIs (often) only support listing the latest 3200 items (ordered by time).

**Comment by AkimParis** [comment]
Yes, the limitation only gave me until Feb 2022 so I created a bespoke script. Thank you Mahrtayyab!

Best,
