### ISSUE TITLE
Make Tweet content appear

### ISSUE THREAD

**Issue by wenithor** [mahrtayyab/tweety#131]
Hello, I'm using the code but when generating the tweets the message content doesn't appear, it just appears: Tweet(id=1577243434032562176, author=User(id=2374513764, username=godiswomanx, name=PORTALS, verified=False), created_on= 2022-10-04 10:25:13+00:00), would it be possible to make the Tweet text appear?

**Comment by dgw** [comment]
Duplicate of #114 and others.

**Comment by wenithor** [comment]
Thank you.
