### ISSUE TITLE
I had a problem trying it out

### ISSUE THREAD

**Issue by lajiduojiaji** [mahrtayyab/tweety#134]
from tweety import Twitter

app = Twitter("session")
app.sign_in("**", "**")
all_tweets = app.get_tweets("elonmusk")
for tweet in all_tweets:
    print(tweet)

Traceback (most recent call last):
  File "F:\Downloads\tweety-main\tweety-main\test.py", line 3, in <module>
    app = Twitter("session")
          ^^^^^^^^^^^^^^^^^^
  File "F:\Downloads\tweety-main\tweety-main\venv\Lib\site-packages\tweety\bot.py", line 34, in __init__
    self.request = self.http = Request(max_retries=10, proxy=self._proxy)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Downloads\tweety-main\tweety-main\venv\Lib\site-packages\tweety\http.py", line 21, in __init__
    self.__guest_token = self._get_guest_token(max_retries)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Downloads\tweety-main\tweety-main\venv\Lib\site-packages\tweety\http.py", line 93, in _get_guest_token
    raise GuestTokenNotFound(None, None, last_response,
tweety.exceptions_.GuestTokenNotFound: Guest Token couldn't be found after 10 retires.

EDIT: Removed sensitive info.

**Comment by mahrtayyab** [comment]
Are you using it on aws or google cloud?

**Comment by lajiduojiaji** [comment]
No，I just ran your code on pycharm.

**Comment by mahrtayyab** [comment]
Please make sure you are on latest source

**Comment by WeridFire** [comment]
I get the same problem from [pythonanywhere.com](https://www.pythonanywhere.com/) but not for my local machine maybe has something to do with proxies?

**Comment by mahrtayyab** [comment]
Added fallback method to get guest token , update to latest version
