### ISSUE TITLE
Incomplete output (?)

### ISSUE THREAD

**Issue by pclavell** [mahrtayyab/tweety#135]
Hello,
I am using the function `get_tweets()` but I am only getting the tweet information so the id and the info from the author, not the content:
`Tweet(id=1738291010038345948, author=User(id=11348282, username=NASA, name=NASA, verified=True)`

And when trying to obtain user info with `get_user_info()` I only get this:
`User(id=11348282, username=NASA, name=NASA, verified=True)`

I do not know if this is a bug or if there is some way to extract the tweet content from this. Thanks and sorry for the inconvenience.

**Comment by mahrtayyab** [comment]
These are the representations of object.
To get tweet text , you need to do `tweet.text` , same for user , more about tweet object [here]('https://mahrtayyab.github.io/tweety_docs/basic/twDataTypes.html#Tweet')

**Comment by pclavell** [comment]
Oh my bad, thanks a lot for the quick response, it works incredibly well! Is there any way to obtain more than 100 tweets per user?

**Comment by mahrtayyab** [comment]
You can use `pages` parameter of `get_tweets` method.

**Comment by pclavell** [comment]
Despite using pages I get the same output always and many tweets are missing, in particular I noticed that all the last month tweets are missing. This is my code:
`from tweety import Twitter
  
app = Twitter("session")

# get tweets from user
all_tweets = app.get_tweets("bsc_cns", pages=5)
my_tweets=[tweet for tweet in all_tweets]

# parse publication date
from datetime import datetime
dates = [tweet.created_on for tweet in my_tweets]
sorted_dates = sorted(dates)

# print in order the date of the tweets
for date in sorted_dates:
    print(date.strftime("%Y-%m-%d %H:%M:%S%z"))`

**Comment by mahrtayyab** [comment]
are you logged in?

**Comment by mahrtayyab** [comment]
@pclavell are you logged in?

**Comment by pclavell** [comment]
I didn't, now I am getting tweets from accounts I previously couldn't. Thanks for your help and sorry for the late answer.
