### ISSUE TITLE
Is tweety right now submitting to Twitter API rate limits ?

### ISSUE THREAD

**Issue by AhmetcanFR** [mahrtayyab/tweety#137]
Hey ! I saw that we need to sign in with a twitter acc in order to use Tweety.

Does that mean we have to consider the API rate limits ? I thought it was working without the rate limitations..

**Comment by dgw** [comment]
It's using the API Twitter's own client (I forget which one) uses, so it's not following the official API's rate limits—but there _are_ still request limits on the undocumented endpoints this library uses.

**Comment by mahrtayyab** [comment]
It would have same limits as web client.

**Comment by fabston** [comment]
@mahrtayyab do you know if verified accounts have higher limits?
