### ISSUE TITLE
listen to new tweets

### ISSUE THREAD

**Issue by fabston** [mahrtayyab/tweety#138]
Hello,

could you recommend a way to listen to new tweets (live)? 

Thank you.

**Comment by sharad-s** [comment]
Ser

**Comment by mahrtayyab** [comment]
the best best will be to create a list, and keep looking for new tweets are regular intervals

**Comment by fabston** [comment]
> the best approach will be to create a list, and keep looking for new tweets are regular intervals in that list

Gotcha, thank you. What would you say how often I can look for new tweets without timeout issues?

**Comment by fabston** [comment]
@mahrtayyab Gotcha, thank you. Am I also able to see replies? Didn't really see them, just sometimes a reply pops up but seems not really stable...

**Comment by kairusds** [comment]
> @mahrtayyab Gotcha, thank you. Am I also able to see replies? Didn't really see them, just sometimes a reply pops up but seems not really stable...

can confirm this, replies aren't up to date

**Comment by mahrtayyab** [comment]
Replies are only become part of list when both users involved in that reply are member of that list
`If user2 is replying to user1 , the reply will only appear in list if user2 is also member of that list`
