### ISSUE TITLE
"UnknownError: Unknown Error Occurs on Twitter" when trying to searched, even though I am logged in 

### ISSUE THREAD

**Issue by wong-andrew** [mahrtayyab/tweety#140]
Hi -- I am logged in to Twitter -- see below: 
<img width="1172" alt="Screen Shot 2024-01-04 at 9 07 15 PM" src="https://github.com/mahrtayyab/tweety/assets/155693065/c48fc462-a625-4b15-a33e-4a165a4cedb6">

And I can view tweets, as follows: 
<img width="1217" alt="Screen Shot 2024-01-04 at 9 07 51 PM" src="https://github.com/mahrtayyab/tweety/assets/155693065/2784a28e-afc2-476e-a520-85cb32a4397d">

But when I try to search Twitter in the following way: 

app = Twitter("session5")
tweets = app.search('christmas',1)
for tweet in tweets:
    print(tweet)

I get the following error:

---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
Cell In[8], line 2
      1 app = Twitter("session5")
----> 2 tweets = app.search('christmas',1)
      3 for tweet in tweets:
      4     print(tweet)

File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tweety/bot.py:180, in BotMethods.search(self, keyword, pages, filter_, wait_time, cursor)
    176     wait_time = 0
    178 search = Search(keyword, self, pages, filter_, wait_time, cursor)
--> 180 list(search.generator())
    182 return search

File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tweety/types/base.py:46, in BaseGeneratorClass.generator(self)
     44 def generator(self):
     45     for page in range(1, int(self.pages) + 1):
---> 46         results = self.get_next_page()
     48         if len(results) == 0:
     49             break

File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tweety/types/search.py:37, in Search.get_next_page(self)
     35 def get_next_page(self):
     36     if self.is_next_page:
---> 37         response = self.client.http.perform_search(self.keyword, self.cursor, self.filter)
     38         thisTweets = self._parse_response(response)
     40         self['is_next_page'] = self.is_next_page

File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tweety/http.py:147, in Request.perform_search(self, keyword, cursor, filter_)
    145 keyword = quote(keyword, safe="()%")
    146 request_data = self.__builder.search(keyword, cursor, filter_)
--> 147 response = self.__get_response__(**request_data)
    148 return response

File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tweety/http.py:70, in Request.__get_response__(self, return_raw, ignore_none_data, is_document, **request_data)
     67     response_json = {"errors": [{"code": 88, "message": "Rate limit exceeded."}]}
     69 if not response_json:
---> 70     raise UnknownError(
     71         error_code=response.status_code,
     72         error_name="Server Error",
     73         response=response,
     74         message="Unknown Error Occurs on Twitter" if not response.text else response.text
     75     )
     77 if response_json.get("errors") and not response_json.get('data'):
     78     error = response_json['errors'][0]

UnknownError: Unknown Error Occurs on Twitter

**Can someone please help?**  I have tried changing the search terms, page limits, using the suggested code, etc and none of those approaches are working

**Comment by wong-andrew** [comment]
It is also worth noting that I have the most up-to-date version of the package loaded, and that issue persists even if I use the auth_token log in approach

**Comment by mahrtayyab** [comment]
``` python

app = Twitter("session5")
tweets = app.search('christmas',1)
for tweet in tweets:
    print(tweet)

```

are you sure , you are calling app.start()

![image](https://github.com/mahrtayyab/tweety/assets/38404705/65031264-c07e-491e-8863-bdd802e96fed)

**Comment by wong-andrew** [comment]
Outside of the first screenshot, how could I validate that?

**Comment by mahrtayyab** [comment]
use `app.me` to get the current logged in user

**Comment by mahrtayyab** [comment]
Update to latest version , it will automatically raise exception when login is required

**Comment by mahrtayyab** [comment]
Issue is being closed for inactivity
