### ISSUE TITLE
How to grab replied tweet

### ISSUE THREAD

**Issue by fabston** [mahrtayyab/tweety#141]
How can I grab the tweet text from a replied tweet? So for example [here](https://x.com/elonmusk/status/1741087997410660402?s=20), how can i grab the tweet data from `@fentasyl`? I was looking into `tweet_detail` but couldnt find it, only the boolean `is_reply`.

**Comment by mahrtayyab** [comment]
In this specific , it is quoted tweet , so you can use `tweet.quoted_tweet.text`.
To get reply to use `tweet.get_reply_to()`

**Comment by fabston** [comment]
Great, ty!
