### ISSUE TITLE
URL not showing

### ISSUE THREAD

**Issue by fabston** [mahrtayyab/tweety#143]
Do you know why [this tweet](https://twitter.com/WuBlockchain/status/1745312885298041012) isn't showing any url in `urls`? Even though there is an URL in the tweet (`https://cointelegraph.com...`)?

Thanks for your help.

**Comment by mahrtayyab** [comment]
It is rich text , try `tweet.rich_text.urls`

**Comment by mahrtayyab** [comment]
Noted , will be added to tweet urls too in next release
