### ISSUE TITLE
check if the tweet was edited

### ISSUE THREAD

**Issue by fabston** [mahrtayyab/tweety#144]
Am I able to check if a tweet was edited or not?

Right now I am listening to new tweets in a list and if a tweet gets edited its being shown as a new tweet, would be great if i could differentiate an edited tweet from a new tweet.

**Comment by fabston** [comment]
The tweet id changes. here is an example:

Initial tweet:
https://twitter.com/Joshyysmartt/status/1746501868879036435

Edited tweet:
https://twitter.com/Joshyysmartt/status/1746501977729593809

**Comment by mahrtayyab** [comment]
Tweet ID changes in order to maintain the history , I was working on this exactly , will be updated in next few hours

**Comment by dgw** [comment]
Wild, I've never seen a platform that generates a new ID for edited content. Will be interesting to see how Tweety exposes this!

**Comment by mahrtayyab** [comment]
Use `tweet.has_newer_version` or `tweet.edit_control.is_latest`
To get latest tweet use `tweet.get_latest()` or `tweet.edit_control.latest`

**Comment by fabston** [comment]
Thanks a lot! Awesome work!
