### ISSUE TITLE
Scrap limit?

### ISSUE THREAD

**Issue by ycngmn** [mahrtayyab/tweety#148]
Hello, 
I know there is an arguement "pages" but even the default =1 returns an impressive numbers of results. I was aking if it was possible to scrap only a desired (smaller) number of results , question of imlroving efficiency.  

Thank you for your project.

**Comment by mahrtayyab** [comment]
you can use `iter_tweets` and as soon as you reach you desire number of tweets , exit the generator.

**Comment by ycngmn** [comment]
> you can use `iter_tweets` and as soon as you reach you desire number of tweets , exit the generator.

Can you please provide an example of how can I achieve that? Sorry, noob here.
