### ISSUE TITLE
User blocking

### ISSUE THREAD

**Issue by umgbhalla** [mahrtayyab/tweety#149]
Is support for block requried? 
i just modified api route for [unfollow](https://github.com/mahrtayyab/tweety/blob/main/src/tweety/builder.py#L65) to https://api.twitter.com/1.1/blocks/create.json and it worked, do we need a pr for implementation with builder and user classes? can wip one if it makes sense to add

**Comment by mahrtayyab** [comment]
Sure always up for PRs

**Comment by umgbhalla** [comment]
@mahrtayyab https://github.com/mahrtayyab/tweety/pull/150
