### ISSUE TITLE
Feature request: use generator for get_tweets

### ISSUE THREAD

**Issue by cqsd** [mahrtayyab/tweety#15]
If `get_tweets` fails midway through (eg, due to network issue, etc), the caller will lose progress and have to refetch. Using a generator would enable the caller to save tweets as pages are fetched. If you're open to this change, I can make a PR.

**Comment by mahrtayyab** [comment]
Hi , yes it is under-development , it will be implemented in the next update , if you still find any shortcomings in implementation, you are welcome to open PR.

**Comment by cqsd** [comment]
thanks
