### ISSUE TITLE
SelfThread init error 

### ISSUE THREAD

**Issue by harleyLuke** [mahrtayyab/tweety#151]
SelfThread init error ,But I don't know is Bug or You just ignore it

![image](https://github.com/mahrtayyab/tweety/assets/117342269/073bedcb-201b-494e-887c-b336113f0cf3)

![image](https://github.com/mahrtayyab/tweety/assets/117342269/2349ca13-6325-4c7a-98ad-de4f4b1d7232)

![image](https://github.com/mahrtayyab/tweety/assets/117342269/841b4c98-3569-4067-817e-9699cd6ccc12)
So,can parse Twitter class,But SeafThread class can't  parse , just pass Error

**Comment by mahrtayyab** [comment]
Thank you , fixed in [7d86e20](https://github.com/mahrtayyab/tweety/commit/7d86e208a82fc5884005518e7ed8c4967b3f52f5)
