### ISSUE TITLE
Mutual Friends for get_user_info

### ISSUE THREAD

**Issue by fabston** [mahrtayyab/tweety#153]
If I am logged into my account, am I able to print the mutual friends count when calling `get_user_info`?

**Comment by mahrtayyab** [comment]
What exactly you mean by  mutual friends
This one `https://twitter.com/<username>/followers_you_follow` ?

**Comment by fabston** [comment]
Yes exactly, the count of `followers_you_follow`.  So that it returns a number. @mahrtayyab

**Comment by mahrtayyab** [comment]
For that we have to make another request , will be added soon

**Comment by fabston** [comment]
Awesome, looking forward to it. Thanks a lot!

**Comment by fabston** [comment]
Hi @mahrtayyab, in the latest commit you added `get_mutual_friend`, is that related to this? Wasn't able to properly call it yet tho, hence I am asking/wondering. Cheers!

**Comment by mahrtayyab** [comment]
Added in latest release

**Comment by fabston** [comment]
Cool, thank you @mahrtayyab. I'd have one more question, if I set pages to `4` does that mean if there are more than 4 pages of mutual followers, the bot will have to hit twitter 4 times? I assume if there are too many pages it could happen that twitter will throttle/time me out?
