### ISSUE TITLE
aws doesnt get all the tweets

### ISSUE THREAD

**Issue by fb0x** [mahrtayyab/tweety#155]
hi everyone, im scraping tweets for 3 users and was running fine locally and deployed on aws. But now I only get the tweets from 2 users not for the third one. I ran a simple script to see if i can get his tweets and it worked fine locally but on aws it doesn't work properly. any idea why? only for this user and his tweets area accessible if i run the code locally

**Comment by mahrtayyab** [comment]
1. Twitter blocks about all AWS IP addresses
2. It is weird , that it is working for some , and not for other , can you please by any chance send the username of the concerned user.

**Comment by fb0x** [comment]
> 1. Twitter blocks about all AWS IP addresses
> 2. It is weird , that it is working for some , and not for other , can you please by any chance send the username of the concerned user.

that's interesting, so where do your recommend me to deploy? other 2 users work fine but this one doens't indeed interesting. 

Is that the case with other servers as well? Like google etc? 

username is : Crypto_Shaggy

also what do you recommend me to do bypass this twitter block?

**Comment by mahrtayyab** [comment]
Use good proxy

**Comment by fb0x** [comment]
> Use good proxy

did it work for you on aws?

**Comment by EsqerYasen** [comment]
> 1. Twitter blocks about all AWS IP addresses
> 2. It is weird , that it is working for some , and not for other , can you please by any chance send the username of the concerned user.

is there any way that can set on proxy for tweety ? I couldn't find in document page.

**Comment by mahrtayyab** [comment]
`Twitter` class accepts an optional argument `proxy`, it could be `dict` or `tweety.types.Proxy`, documentation is outdated right now, I will update it soon.

``` python

from tweety import Twitter
from tweety.types import Proxy, PROXY_TYPE_HTTP

proxy = Proxy(host="127.0.0.1", port=8080, proxy_type=PROXY_TYPE_HTTP, username="username", password="password")

client = Twitter("session", proxy=proxy)

```

**Comment by EsqerYasen** [comment]
> ```python
> proxy=proxy
> ```
thank you so! this helps.

**Comment by EsqerYasen** [comment]
> `Twitter` class accepts an optional argument `proxy`, it could be `dict` or `tweety.types.Proxy`, documentation is outdated right now, I will update it soon.
> 
> ```python
> from tweety import Twitter
> from tweety.types import Proxy, PROXY_TYPE_HTTP
> 
> proxy = Proxy(host="127.0.0.1", port=8080, proxy_type=PROXY_TYPE_HTTP, username="username", password="password")
> 
> client = Twitter("session", proxy=proxy)
> ```

thank you so much! this helps.
