### ISSUE TITLE
Check if a tweet replies are open

### ISSUE THREAD

**Issue by fabston** [mahrtayyab/tweety#157]
Are we able to check if a tweet's replies are open or limited? Referring to limits like and this call `tweet_detail`:

![img](https://i.ibb.co/xD2VKtf/SCR-20240125-ogih.png)

**Comment by mahrtayyab** [comment]
right now you can check that in `_original_tweet` attribute of `Tweet`

**Comment by mahrtayyab** [comment]
Added in latest version , `can_reply` in `Tweet`

**Comment by fabston** [comment]
Awesome, thanks a lot fren!

**Comment by mahrtayyab** [comment]
Can you please send the tweet id if possible.

**Comment by mahrtayyab** [comment]
The GrahpQL response has been changed from "conversation_control" to "limitedActionResults", will be fixed in next few hours

**Comment by mahrtayyab** [comment]
https://github.com/mahrtayyab/tweety/commit/6eecee0f44ad986d7209cda91fc4390810edda8c
