### ISSUE TITLE
create_tweet with alt_texts

### ISSUE THREAD

**Issue by Jamie1605** [mahrtayyab/tweety#158]
I saw the added attribute of "alt_text" to media files of a tweet, but is there a way to add alt texts to one or multiple images of a tweet via the create_tweet function?

**Comment by mahrtayyab** [comment]
`files` argument of `create_tweet` accepts either
1. filename which is str
2. UploadedMedia instance
3. tuple or list of (filename or UploadedMedia ) and str

second string in tuple is the alt text for that media.

**Comment by Jamie1605** [comment]
How exactly would that files list be built for multiple images? Because I tried `files=['image1.png', 'alttext1', 'image2.png', 'alttext2']` and that doesn't seem to be it

**Comment by mahrtayyab** [comment]
It would be
`files=[('image1.png', 'alt text 1'), ('image2.jpg', 'alt text 2')]`
