### ISSUE TITLE
how to crawl tweets for a specified time period？

### ISSUE THREAD

**Issue by elberttreble** [mahrtayyab/tweety#161]
May I ask what kind of settings can be used to crawl tweets for a specified time period from an account? Because now it seems that the number of crawled tweets can only be controlled by setting the page. Or, how can I see on a Twitter webpage where a tweet is located?

Thanks~

**Comment by mahrtayyab** [comment]
Use twitter advance search

**Comment by mahrtayyab** [comment]
Like 

``` python
...

tweets = client.search("(from:elonmusk until:2023-12-31 since:2022-01-01)")
```
