### ISSUE TITLE
Request for retrieving "Following" home timeline

### ISSUE THREAD

**Issue by middlingphys** [mahrtayyab/tweety#163]
Is there a way to retrieve the content of the "Following" home timeline instead of "For you"? On Twitter's website, it seems that the former is obtained using the ``HomeLatestTimeline`` endpoint, while the latter is obtained using ``HomeTimeline``. However, it appears that tweety does not currently implement a method to call the ``HomeLatestTimeline`` endpoint. If that's the case, I'd like to request the implementation of this feature.

**Comment by mahrtayyab** [comment]
Sure , it will be added soon

**Comment by mahrtayyab** [comment]
Added in latest release

``` python

from tweety.types import HOME_TIMELINE_TYPE_FOLLOWING
...

timeline = client.get_home_timeline(timeline_type=HOME_TIMELINE_TYPE_FOLLOWING)
print(timeline[0]) # Tweet
```
