### ISSUE TITLE
Potential bug in "get_user_followings"

### ISSUE THREAD

**Issue by fabston** [mahrtayyab/tweety#164]
The code below returns `AttributeError: 'int' object has no attribute 'lower'`, while I dont have any issues using other IDs.

```py
app = Twitter("session")
app.connect()

following = app.get_user_followings(1407978258721738752)
print(following)
```

**Comment by mahrtayyab** [comment]
Thank you for pointing out , it looks a user as only numbers as username , and the lib is parsing it as a integer , will be fixed in next release

**Comment by fabston** [comment]
Great, thank you!

**Comment by mahrtayyab** [comment]
Fixed in latest release
