### ISSUE TITLE
 Unable to tweet or reply tweets using Library

### ISSUE THREAD

**Issue by Balogunolalere** [mahrtayyab/tweety#165]
I'm encountering an issue while trying to tweet using the library within my application. Here's a shortened version of the code I tried:

    app.create_tweet('backend development', reply_to="1756642807911977329")

Expected Behavior:

The code should create a new tweet with the text "backend development" and reply to the tweet with ID "1756642807911977329".

Actual Behavior:

Unfortunately, the tweet is not being created. I'm unsure if the reply functionality is working correctly or if there's another issue preventing the tweet from being sent.

**Comment by mahrtayyab** [comment]
Is there any Exception raised while doing so.

**Comment by Balogunolalere** [comment]
nope, when i check my timeline on web i don't see tweet or reply

**Comment by mahrtayyab** [comment]
It should be returning `Tweet` object then, can you confirm that?

**Comment by Balogunolalere** [comment]
yes i can confirm
    Tweet(id=1757014437909946506, author=User(id=1506909462468116481, username=OlalereBalogun, name=olalere balogun, verified=False), created_on=2024-02-12 12:11:00+00:00)

**Comment by mahrtayyab** [comment]
https://twitter.com/OlalereBalogun/status/1757014437909946506, it is posted

**Comment by mahrtayyab** [comment]
Also visible in replies

**Comment by Balogunolalere** [comment]
silly me, must have used a different account with the library (i am using a old session file) thanks alot
