### ISSUE TITLE
Feature｜Any plan for support tweet translate?

### ISSUE THREAD

**Issue by EsqerYasen** [mahrtayyab/tweety#166]
I know it's not very important, but twitter has a translate feature, I wander if you have any plan to support?
like with some Arguments, return translated tweet key in tweet info to spefic language.

**Comment by mahrtayyab** [comment]
Sure it will be added in next release

**Comment by mahrtayyab** [comment]
Added in latest release

``` python
from tweety.filters import Language
...
tweet = client.tweet_detail("tweet_id")
print(tweet.translate(Language.English).text)

```
