### ISSUE TITLE
KeyError: 'Content-Length' Issue with downloading meda

### ISSUE THREAD

**Issue by Narcissus13** [mahrtayyab/tweety#167]
I kept hitting the below issue when trying to download media (like 10 tweets in):

```
Traceback (most recent call last):
  File "C:\Users\X\Desktop\ScrapedTweets\ScrapeTw.py", line 56, in <module>
    media.download(path)
  File "C:\Users\X\AppData\Roaming\Python\Python310\site-packages\tweety\types\twDataTypes.py", line 874, in download
    return self._client.http.download_media(url, filename, progress_callback)
  File "C:\Users\X\AppData\Roaming\Python\Python310\site-packages\tweety\http.py", line 428, in download_media
    total_size = int(response.headers['Content-Length'])
  File "C:\Python310\lib\site-packages\httpx\_models.py", line 226, in __getitem__
    raise KeyError(key)
KeyError: 'Content-Length'
```

I haven't done any substantial debugging, but noting switching http.py line428 datatype from int to float seems to improve it for me (although I still eventually hit it). My guess is then that there's some overflow when passing it to int?

**Comment by Narcissus13** [comment]
Also If you could provide an example of using Advanced Search with Tweety.py that would be much appreciated! I'm only getting the first page of results using the search method and the adjacent query!

```
query = '(from:elonmusk until:2023-12-31 since:2022-01-01)'
all_tweets = app.search(query,20,None,15,None)
```

**Comment by mahrtayyab** [comment]
> Also If you could provide an example of using Advanced Search with Tweety.py that would be much appreciated! I'm only getting the first page of results using the search method and the adjacent query!
> 
> ```
> query = '(from:elonmusk until:2023-12-31 since:2022-01-01)'
> all_tweets = app.search(query,20,None,15,None)
> ```

Use Latest filter

**Comment by mahrtayyab** [comment]
> I kept hitting the below issue when trying to download media (like 10 tweets in):
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\X\Desktop\ScrapedTweets\ScrapeTw.py", line 56, in <module>
>     media.download(path)
>   File "C:\Users\X\AppData\Roaming\Python\Python310\site-packages\tweety\types\twDataTypes.py", line 874, in download
>     return self._client.http.download_media(url, filename, progress_callback)
>   File "C:\Users\X\AppData\Roaming\Python\Python310\site-packages\tweety\http.py", line 428, in download_media
>     total_size = int(response.headers['Content-Length'])
>   File "C:\Python310\lib\site-packages\httpx\_models.py", line 226, in __getitem__
>     raise KeyError(key)
> KeyError: 'Content-Length'
> ```
> 
> I haven't done any substantial debugging, but noting switching http.py line428 datatype from int to float seems to improve it for me (although I still eventually hit it). My guess is then that there's some overflow when passing it to int?

Fixed in latest release
