### ISSUE TITLE
The number of crawled tweets is far less than the parameter settings

### ISSUE THREAD

**Issue by elberttreble** [mahrtayyab/tweety#168]
The account I want to crawl has more than 3000 tweets, using the following code no matter how many pages are set, it can only crawl 843 tweets all the time, may I know why?（I also tried to crawl another Twitter account, and the same situation happened）

tweets = app.get_tweets(target_username,200,wait_time=5)

**Comment by mahrtayyab** [comment]
https://github.com/mahrtayyab/tweety/wiki/FAQs#twitter-new-limits
