### ISSUE TITLE
feature: unlock method

### ISSUE THREAD

**Issue by mintertale** [mahrtayyab/tweety#169]
Hi, really liked your library for working with tweets. But it would be great to also have an account unlock feature when Twitter offers to solve arkose captcha which can be sent to solver services such as 2captcha, anticaptcha and many others7

**Comment by mahrtayyab** [comment]
It is planned , but would require significant amount of time.

**Comment by mahrtayyab** [comment]
Added in latest update

**Comment by ljk1291** [comment]
Hi, thanks for your great work! Do you have an example of how to use the anticaptcha with 2captcha?
