### ISSUE TITLE
Bug in "get_user_followings"

### ISSUE THREAD

**Issue by fabston** [mahrtayyab/tweety#171]
I have noticed that for a few accounts i am not able to grab their following, it just returns 0 while they follow accounts.

A few accounts that are effected: [@VMNFT93](https://x.com/VMNFT93), [@0xd063](https://x.com/0xd063), [@ahboyash](https://x.com/ahboyash).

**Comment by mahrtayyab** [comment]
![image](https://github.com/mahrtayyab/tweety/assets/38404705/d6f9d52b-7e1e-46bb-9c29-254a62a25b0a)

**Comment by fabston** [comment]
Oh ok, must be because he got restricted I guess? The other two got followings tho

**Comment by mahrtayyab** [comment]
![image](https://github.com/mahrtayyab/tweety/assets/38404705/dd12e008-2315-42c9-ad2f-7154b0da705a)

if you can send the code snippet you are running

**Comment by fabston** [comment]
```py
from tweety import Twitter

app = Twitter("session")
app.connect()

followings = app.get_user_followings(986054149920866305) # @ahboyash
print(followings)
for follow in followings:
    print(follow)
```

which prints: `UserFollowings(user_id=986054149920866305, count=0)`

**Comment by mahrtayyab** [comment]
![image](https://github.com/mahrtayyab/tweety/assets/38404705/e073d423-d3bf-4485-9d6e-63832e1d59f8)
are you updated?

**Comment by fabston** [comment]
I am on version `1.0.9.5`. Just ran `pip install https://github.com/mahrtayyab/tweety/archive/main.zip --upgrade ` again so I assume I am?
