### ISSUE TITLE
Issuie in types.usertweet.UserTweets

### ISSUE THREAD

**Issue by faycal-rakza** [mahrtayyab/tweety#174]
Hello, sometimes there is no attribute `is_retweet`

Code example :
```python
all_tweets = app.get_tweets("user")

for tweet in all_tweets:
   if not tweet.is_retweet:
```

Error : `'SelfThread' object has no attribute 'is_retweet'`

**Comment by mahrtayyab** [comment]
[SelfThread](https://mahrtayyab.github.io/tweety_docs/basic/twDataTypes.html#SelfThread) is the list of tweets , you need to iterate over it.

``` python
from tweety.types import SelfThread
...

for tweet in all_tweets:
    if isinstance(tweet, SelfThread):
        for t_tweet in tweet:
            print(t_tweet)

```
