### ISSUE TITLE
QuotedTweet should be a SelfQuote

### ISSUE THREAD

**Issue by BenjaminIrwin** [mahrtayyab/tweety#176]
Firstly, thanks for your amazing work. This library is fantastic.

My question: when a QuotedTweet is actually a thread (e.g. like this [tweet, which quotes a thread](https://twitter.com/iAdnanAamir/status/1758407409880412658)), that QuotedTweet should surely be a SelfQuote? Instead that QuotedTweet is just a normal Tweet object, and as a result you can't programatically access the rest of the tweets in the quoted thread.

For a repeatable example: when I fetch the tweet above as part of app.get_tweets('username'), I get the following:

```
  "retweeted_tweet": null,
  "rich_text": null,
  "text": "Please read this thread to understand the dire status of the economy and why the current controversial election will only exacerbate the crisis.\n\ud83d\udc47",
  "tweet_body": "Please read this thread to understand the dire status of the economy and why the current controversial election will only exacerbate the crisis.\n\ud83d\udc47",
  "is_quoted": "True",
"quoted_tweet": {
    "id": "1756790439787594026",
    "created_on": "2024-02-11T21:20:55+00:00",
    "date": "2024-02-11T21:20:55+00:00",
    "author": {
      ...
    },
    "has_newer_version": "False",
    "broadcast": null,
    "threads": [],
    "is_liked": "False",
    "is_retweeted": "False",
    "can_reply": "True",
    "comments": []
  },
```

Is this a bug or deliberate or am I missing something?

Thanks

**Comment by mahrtayyab** [comment]
This is server sided , Thread is basically collection of individual Tweet , while Quoting Tweet you are quoting only one Tweet not whole thread , so in that case `quoted_tweet` has that specific `Tweet`  only. To get threads you can use `tweet_detail`.
