### ISSUE TITLE
Getting "'NoneType' object has no attribute 'json_'" in some functions

### ISSUE THREAD

**Issue by taumaturgodedatos** [mahrtayyab/tweety#179]
I´m getting the following:

`'NoneType' object has no attribute 'json_'`

When runing functions like:

`app.get_blocked_users().users`

`app.get_user_followers(username)`

but the following works fine:

`app.get_user_info(username)`

This started from one day to another. I´m using Python 3.9.18.

**Comment by mahrtayyab** [comment]
Can you please specify library version?

**Comment by mahrtayyab** [comment]
Fixed in latest version
