### ISSUE TITLE
`quoted_tweet` data missing when `is_quoted` is True

### ISSUE THREAD

**Issue by dgw** [mahrtayyab/tweety#18]
```python
from tweety.bot import Twitter
app = Twitter()
t = app.tweet_detail('1644327757906685959')
t.is_quoted  # True
t.quoted_tweet  # None

t.urls  # includes URL info for the quoted tweet, as below:
# [{'display_url': 'twitter.com/learnwithmattc…', 
#   'expanded_url': 'https://twitter.com/learnwithmattc/status/1644241752520372225',
#   'url': 'https://t.co/PWJpWPPhnK', 'indices': [263, 286]}]
```

As yet I have been unable to find any example tweets where `quoted_tweet` data is populated. However, for basic usage in my project, the fixes for #11 and other issues that have been closed since I last tried to migrate away from the official API are _very much_ appreciated!

**Comment by mahrtayyab** [comment]
Please do try now

**Comment by dgw** [comment]
With `tweety-ns` 0.6.1 it seems to work now, yes. Thank you so much!
