### ISSUE TITLE
Can't show tweets of list

### ISSUE THREAD

**Issue by FunkedelicBob** [mahrtayyab/tweety#182]
Hey, I saw you mention using the function `get_list_tweets` but I can't seem to get it to work. Can you have a look at my example code?

```
from tweety import Twitter

app = Twitter("session")
app.sign_in('username', 'password')

list_id = "1234567890"  # Replace this with the actual list ID

list_tweets = app.get_list_tweets(list_id)

for tweet in list_tweets.tweets:
    print(tweet)
```

**Comment by mahrtayyab** [comment]
What exactly is the error?

**Comment by FunkedelicBob** [comment]
> What exactly is the error?

```
list_tweets = app.get_list_tweets(list_id)
AttributeError: 'Twitter' object has no attribute 'get_list_tweets'
```

**Comment by FunkedelicBob** [comment]
Running on 3.10.1
And I just ran:
`pip install --upgrade tweety`

**Comment by mahrtayyab** [comment]
try uninstall and reinstall

**Comment by FunkedelicBob** [comment]
> try uninstall and reinstall
> 

Good call. I'll do it first thing tomorrow morning and let you know. I really appreciate the quick replies!

**Comment by mahrtayyab** [comment]
it is `tweety-ns` not `tweety`

**Comment by FunkedelicBob** [comment]
> it is `tweety-ns` not `tweety`

Thanks, but it was actually pip. It is installing version 0.9.9.5 instead of 1.1.2

**Comment by mahrtayyab** [comment]
You can use `pip install tweety-ns==1.1.2`
