### ISSUE TITLE
How can we get all the comments on a post ?

### ISSUE THREAD

**Issue by Rgwww** [mahrtayyab/tweety#192]
I'm using your project interface to get comment data from a user's post, But when I use the app.get_tweet_comments method, getting the comments doesn't match what I get on the page. 
`
app.get_tweet_comments("1798731573723815974", 1, cursor = 'PAAAAPAtPBwcFr7E1vGNnr32MRUCAAAYJmNvbnZlcnNhdGlvbnRocmVhZC0xNzk4NzQ3MDk4MTU1OTgzMjc0IgAA', get_hidden = True)
`
I read the documentation and couldn't find a way to fix it,
<img width="508" alt="5e6d3ba2b29e265971f8c4217b6626a" src="https://github.com/mahrtayyab/tweety/assets/40284121/00d26e91-00be-4451-89b4-1c412d73ec1d">
<img width="473" alt="206ef62a7e4ac089db5b15dee7364c7" src="https://github.com/mahrtayyab/tweety/assets/40284121/ed73d5a2-0701-44f9-81d4-db2e2e04b3d7">

**Comment by mahrtayyab** [comment]
`get_tweet_comments` return [TweetComments](https://mahrtayyab.github.io/tweety_docs/basic/twDataTypes.html#tweetcomments) object, has attribute `tweets` which are basically the list of tweets. Iterating over this list will give you [ConversationThread](https://mahrtayyab.github.io/tweety_docs/basic/twDataTypes.html#ConversationThread)

**Comment by Rgwww** [comment]
> `get_tweet_comments`返回[TweetComments](https://mahrtayyab.github.io/tweety_docs/basic/twDataTypes.html#tweetcomments)对象，其属性`tweets`基本上是 ConversationThread 的列表。
> 
> 迭代此列表将为你提供[ConversationThread](https://mahrtayyab.github.io/tweety_docs/basic/twDataTypes.html#ConversationThread)对象`tweets`，该对象具有 Tweets 列表的属性
> 
> 迭代 ConversationThread 将为您提供[Tweet](https://mahrtayyab.github.io/tweety_docs/basic/twDataTypes.html#Tweet)对象。在此对象上，您可以获得`text`属性来获取文本。
> 
> ```python
> comments = client.get_tweet_comments("1798731573723815974", 1, get_hidden=True)
> for _thread in comments:
>     print(_thread) # This is ConversationThread
>     for comment in _thread:
>         print(comment) # This is Tweet
>         print(comment.text)
>         print(comment.media)
> ```

Just like this post, there are 3 comments in the web post of tweets[0], and only 2 comments in the iterative access. Although there is a cursor, I also tried to use the cursor to obtain the third comment, but it still couldn't be obtained. Is it that the api of this project can't support more levels of comment data

**Comment by mahrtayyab** [comment]
You can call `.expand()` method on `ConversationThread` if you to get all tweets of that thread

**Comment by Rgwww** [comment]
I'll try again. Thank you very much
