### ISSUE TITLE
Get tweets from a specific date range

### ISSUE THREAD

**Issue by trevor-nomadik** [mahrtayyab/tweety#194]
Is there a way to get tweets from a specific date range or do I just have to set the pages to an extremely large number to get historical tweets? I imagine this is probably the answer due to the way tweets are loaded on the web.

**Comment by dgw** [comment]
This was _just_ answered two weeks ago in #190

**Comment by trevor-nomadik** [comment]
@dgw What if i only want tweets from a specific user in the date range? This seems to just get me mentions

**Comment by dgw** [comment]
`from:twitterusername since:start-date until:end-date`

This is a "Twitter search syntax" question, not really a "how do I use this library" question.

**Comment by mahrtayyab** [comment]
https://github.com/mahrtayyab/tweety/wiki/FAQs#advance-search
