### ISSUE TITLE
No mute the followed user posts function, please add.

### ISSUE THREAD

**Issue by Jaden024** [mahrtayyab/tweety#196]
No mute the followed user posts function, please add. Don't want to seem rude, I really love tweety, thx for all the hard work, dev!

**Comment by dgw** [comment]
What does a "mute the followed user posts function" do? Is it this? https://help.x.com/en/using-x/x-mute

**Comment by Jaden024** [comment]
> What does a "mute the followed user posts function" do? Is it this? https://help.x.com/en/using-x/x-mute

Yeah, it is exactly what I was talking about, really need it for one of my projects but I didn't figure out how to make a custom post request with Tweety session

**Comment by Jaden024** [comment]
> What does a "mute the followed user posts function" do? Is it this? https://help.x.com/en/using-x/x-mute

Yeah, exactly, tried to make it myself but didn't figure out how to make custom post requests with Tweety session, really need it for one of my projects

**Comment by mahrtayyab** [comment]
Added `mute_user` in latest update
