### ISSUE TITLE
Issue with Extracting Direct Video URL from Tweets

### ISSUE THREAD

**Issue by issim91** [mahrtayyab/tweety#198]
I'm trying to get a link to the media (for video), but the URL contains only the short URL of the tweet (https://t.co/OtvCliDFS5)

Apparently, something has changed on Twitter's side, and now clicking on this link redirects me to the tweet.

Is it possible to get a direct link to the video if it is in the tweet content?

**Comment by mahrtayyab** [comment]
Please post your code snippet

**Comment by issim91** [comment]
`from tweety import Twitter
from tweety.types import Proxy, twDataTypes


proxy =  Proxy(PROXY_URL, 10000, 3, username=PROXY_USERNAME, password=PROXY_PASSWORD)
app = Twitter('session', proxy=proxy)
    
all_tweets = app.get_list_tweets(tw_list, pages=1)

for tweet in all_tweets:
    media = []
    for m in tweet.media:
        media.append({
            'type': m.type,
            'url': m.url,
            'preview_image_url': m.media_url_https,
        })

    tweet_format = {
        'id': tweet.id,
        'text': tweet.text,
        'media': media,
    }`

**Comment by mahrtayyab** [comment]
![image](https://github.com/user-attachments/assets/6a3fa305-a6c5-4281-88a4-ff149ebb469e)
It could be a temporay issue , it is fine for me right now.

**Comment by mahrtayyab** [comment]
![image](https://github.com/user-attachments/assets/2fed7a91-0b3c-4881-9ce1-54eb2b29b331)
Video is okay too.

**Comment by issim91** [comment]
Thank you! Video urls from Stream working

**Comment by issim91** [comment]
Thank you! Video urls from Stream working
