### ISSUE TITLE
keyError: 'globalObjects'

### ISSUE THREAD

**Issue by jael-toledo** [mahrtayyab/tweety#20]
![tweety](https://user-images.githubusercontent.com/107224315/234414428-e27b9063-ca43-4e5f-a1ab-98f7354710a9.png)

 Hello, I am having this error when I try to search by keyword, I would really appreciate it if you could help me to solve it

**Comment by mahrtayyab** [comment]
Hi , Please do check the issue #12

**Comment by mahrtayyab** [comment]
It is fixed , do upgrade to latest version and **please** do check full documentation before upgrading
