### ISSUE TITLE
Denied login

### ISSUE THREAD

**Issue by guntherjugend** [mahrtayyab/tweety#201]
Hello, have issue:
[2024-07-31 03:34:26] [ERROR] [Twitter] [DeniedLogin] Suspicious login prevented. We blocked an attempt to access your account because we weren't sure it was really you.

This happens when we notice unusual login activity, like an attempt to log in too many times, or from a different location or device.

You'll need to wait before trying to log in again. Some blocks are removed automatically.

Get help with login issues.

How to avoid this? Old sessions files already added but it still the same.

**Comment by mahrtayyab** [comment]
- Are you on latest version?
- Are you using proxy?

**Comment by guntherjugend** [comment]
Yes and yes. Thank u for reply, but I already fix this. Just renew manually session file with cookies from browser.

**Comment by isntfunny** [comment]
Same here, the loging seems to be impossible all of the sudden:

```
tweety.exceptions.DeniedLogin: Suspicious login prevented. We blocked an attempt to access your account because we weren't sure it was really you.

This happens when we notice unusual login activity, like an attempt to log in too many times, or from a different location or device.

You'll need to wait before trying to log in again. Some blocks are removed automatically.

Get help with login issues.
```

**Comment by mahrtayyab** [comment]
Working on fix , will be pushed in a day

**Comment by YmanChris** [comment]
> Working on fix , will be pushed in a day

Hello, I get same error. Has it updated? Tkx.

**Comment by americaanspirit** [comment]
Same error any update?

**Comment by mahrtayyab** [comment]
It works when using a rotating proxy , suggesting might be a IP bans from Twitter , need further investigation.

**Comment by YmanChris** [comment]
> Yes and yes. Thank u for reply, but I already fix this. Just renew manually session file with cookies from browser.

User your methods, Successed! 🙏

**Comment by changchiyou** [comment]
Any updates? I've been encountering the same error with account/password login for several days now:

<img width="1031" alt="image" src="https://github.com/user-attachments/assets/36e50e59-cd3b-4d4c-80d8-38e0b6e25ae6">

**Comment by Opennes99** [comment]
Yeah i have similar issue as well and get this error  
" ActionRequired: Check your email. In order to protect your account from suspicious activity, we've sent a confirmation code to ***********@******.***. Enter it below to sign in." 

but I never receive any code on the email , do we need to rotate accounts as well as proxies ?

**Comment by simrankapoorr** [comment]
I am using a VPN while logging in and still getting this issue, even if I create new accounts. How to fix?

**Comment by mahrtayyab** [comment]
https://github.com/mahrtayyab/tweety/commit/650981ce9605e6e06f2c5c1fe2db5c01a5270d2e
