### ISSUE TITLE
error executing tweet_detail

### ISSUE THREAD

**Issue by rinaldi6109** [mahrtayyab/tweety#202]
Executing the following code:

> print(app.tweet_detail("https://twitter.com/Microsoft/status/1442542812197801985"))

I get the following error. Why?

> Traceback (most recent call last):
>   File "<pyshell#12>", line 1, in <module>
>     print(app.tweet_detail("https://twitter.com/Microsoft/status/1442542812197801985"))
>   File "...\tweety\bot.py", line 846, in tweet_detail
>     response = self.request.get_tweet_detail(tweetId)
>   File "...\tweety\http.py", line 303, in get_tweet_detail
>     response = self.__get_response__(**self._builder.tweet_detail_as_guest(tweetId))
>   File "...\tweety\http.py", line 168, in __get_response__
>     raise TwitterError(
> tweety.exceptions.TwitterError: Page not Found. Most likely you need elevated authorization to access this resource
> 

I'm using Python.exe 3.12.5 on win 10 with admin privileges.

**Comment by mahrtayyab** [comment]
try using proxy

**Comment by HamedAkhavan** [comment]
@mahrtayyab I see this error using other methods too, although I'm using proxy. What's the cause of this error?
