### ISSUE TITLE
.get_tweet_quotes() no more available

### ISSUE THREAD

**Issue by JArma19** [mahrtayyab/tweety#203]
Hi, I am facing the following issue:

Given the following piece of code
`quotes = app.get_tweet_quotes(tweet.id, pages=pages, wait_time=wait_time)`

It throws this error:
`AttributeError: 'Twitter' object has no attribute 'get_tweet_quotes'`

However, I am sure it worked until a few months ago. 
Could you please help me understand that? 
Is there any workaround to get tweet quotes given the ID?

**Comment by mahrtayyab** [comment]
It is still available
https://github.com/mahrtayyab/tweety/blob/main/src/tweety/user.py#L178

Try reinstalling library
