### ISSUE TITLE
No option to add user into the chat group 

### ISSUE THREAD

**Issue by Jaden024** [mahrtayyab/tweety#205]
No option to add user into the chat group, I would appreciate it a lot if you could add this feature, thanks a lot in advance

**Comment by mahrtayyab** [comment]
This option is available , documentation is not yet updated 
https://github.com/mahrtayyab/tweety/blob/a579be1c06751711139e2c2e79be26c6f2d1a685/src/tweety/user.py#L390C9-L390C28
