### ISSUE TITLE
tweet_detail() method returns InvalidTweetIdentifier exception

### ISSUE THREAD

**Issue by microkate** [mahrtayyab/tweety#21]
Hey there!

Following code:
`from tweety.bot import Twitter`

`app = Twitter()`

`tweet = app.tweet_detail("https://twitter.com/ShouldHaveCat/status/1652093480179466240")`
`print(tweet)`

Returns an InvalidTweetIdentifier exception, but the link is valid and public:

`/home/.../scraperling_birdy/venv/bin/python /home/.../scraperling_birdy/tweetyer.py `

`Traceback (most recent call last):`
`  File "/home/.../scraperling_birdy/tweetyer.py", line 10, in <module>`
`    user = app.tweet_detail("https://twitter.com/ShouldHaveCat/status/1652093480179466240")`
`  File "/home/.../scraperling_birdy/venv/lib/python3.8/site-packages/tweety/bot.py", line 194, in tweet_detail`
`    raise InvalidTweetIdentifier()`
`tweety.exceptions_.InvalidTweetIdentifier: The Identifier provided of the tweet is either invalid or the tweet is private`

`Process finished with exit code 1`

Is it a bug or am I not seeing something? Thank you in advance & take care :)

**Comment by mahrtayyab** [comment]
Hi, I was a able to reproduce this error right now , It will be fixed in next update in 2 days.

**Comment by mahrtayyab** [comment]
It is fixed , do upgrade to latest version and **please** do check full documentation before upgrading
