### ISSUE TITLE
X API denied - "Access to api.x.com was denied"

### ISSUE THREAD

**Issue by seleron** [mahrtayyab/tweety#218]
Hey

As of a couple of hours ago, I am failing to authenticate with tweety-ns, manual methods still work so it's probably not an account access issue. Other friends across the world also experience the same issue.

Over console, getting this message: [34] Sorry, that page does not exist

When clicked on the api link, getting 403 error "Access to api.x.com was denied. You don't have authorisation to view this page."

**Comment by zaksiddiqengineer** [comment]
everyone is getting this error now : [34] Sorry, that page does not exist

it seems tweety has gone down.

**Comment by Jaden024** [comment]
> everyone is getting this error now : [34] Sorry, that page does not exist
> 
> it seems tweety has gone down.

Do you think he's going to fix it? It was 5 month since he has updated anything

**Comment by mahrtayyab** [comment]
> Hey
> 
> As of a couple of hours ago, I am failing to authenticate with tweety-ns, manual methods still work so it's probably not an account access issue. Other friends across the world also experience the same issue.
> 
> Over console, getting this message: [34] Sorry, that page does not exist
> 
> When clicked on the api link, getting 403 error "Access to api.x.com was denied. You don't have authorisation to view this page."

can you please provide more traceback.

**Comment by mahrtayyab** [comment]
> It was 5 month since he has updated anything

Yes, it is updated with async and new fixes , just working on login to be fixed.

**Comment by mahrtayyab** [comment]
> > It was 5 month since he has updated anything
> 
> Yes, it is updated with async and new fixes , just working on login to be fixed.



> > everyone is getting this error now : [34] Sorry, that page does not exist
> > it seems tweety has gone down.
> 
> Do you think he's going to fix it? It was 5 month since he has updated anything

Yes , async update is ready , just working on login to be fixed.

**Comment by seleron** [comment]
I can confirm this was a temporary issue on Twitter and seems to be fixed on my end as well. Closing issue.
