### ISSUE TITLE
Is there a way to get groups as list and not as coroutine?

### ISSUE THREAD

**Issue by Jaden024** [mahrtayyab/tweety#223]
Is there a way to get groups as list and not as coroutine?

In other words, is there a way to use synced version of tweety?

**Comment by Jaden024** [comment]
Idk if the synced version is going to be supported or updated, but the async update definitely messed up the synced flow, the lists are coroutines now and some action like .add_member_to_group and .follow_user want to be awaited

**Comment by Jaden024** [comment]
Also, I think add_member_to_group action does not work at all

**Comment by mahrtayyab** [comment]
Sync is just a little hack , may not work for all methods , I will try to improve it but can't guarantee.

![image](https://github.com/user-attachments/assets/73c69402-b79f-4902-8501-15b9921080a2)
What do mean by "get groups"?

**Comment by mahrtayyab** [comment]
Pushed an improved sync version, do consider upgrading.

**Comment by Jaden024** [comment]
> Sync is just a little hack , may not work for all methods , I will try to improve it but can't guarantee.
> 
> ![image](https://private-user-images.githubusercontent.com/38404705/389247530-73c69402-b79f-4902-8501-15b9921080a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTEwMjcsIm5iZiI6MTczMjQ5MDcyNywicGF0aCI6Ii8zODQwNDcwNS8zODkyNDc1MzAtNzNjNjk0MDItYjc5Zi00OTAyLTg1MDEtMTViOTkyMTA4MGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDIzMjUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYjAzOTNkNmRiMjQ4MzU0NTAyNDIwMTc5OWE3ZDU3M2NhOWY1Y2E2OWZhZjUyNTAyMTI4MDk3Y2EwMTA1NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BNzvbKNiBgVg4khamkbLiNsP8BBQZVAZNUXIEiHnLic) What do mean by "get groups"?

What I meant is the .get_inbox method, it also can't run through sync, I didn't check after the update though

**Comment by Jaden024** [comment]
get_inbox works now, but when logging in and adding subscribing to user gives me an error "invalid cookies"

Here's the function I made that gives me this error:

def add_to_friends(acc_str, user_to_add):

            acc_name, email, password, proxy_str, auth_token = acc_str

            try:

                proxy_ip, proxy_port, proxy_user, proxy_pass = proxy_str.split(':')

                proxy_url = f'http://{proxy_user}:{proxy_pass}@{proxy_ip}:{proxy_port}'

                app = Twitter(f"{script_dir}/sessions/{acc_name}", proxy=proxy_url)
                app.load_auth_token(auth_token)
                app.connect()

                user = app.get_user_info(user_to_add)

                if not user.following:
                    app.follow_user(user.id)
                    print(f'{acc_name} | ' + colored(f'@{user_to_add} Followed Succesfully', 'green'))
                else:
                    print(f'{acc_name} | ' + colored(f'@{user_to_add} was Already Followed', 'green'))
            except Exception as e:
                print(f'{acc_name} | ' + colored(f'Couldn`t Follow @{user_to_add} | Error: {e}', 'red'))

**Comment by mahrtayyab** [comment]
can you please post full traceback

**Comment by Jaden024** [comment]
I'm sorry I think that everything is okay with the library, I don't get this error anymore and sorry once again for the late reply
