### ISSUE TITLE
python-magic broken on windows

### ISSUE THREAD

**Issue by Neppu-Nep** [mahrtayyab/tweety#229]
Current tweety uses `python-magic` library but it has broken interactions on windows and fails with
`ImportError: failed to find libmagic.  Check your installation`

Manually pip installing `python-magic-bin` on top of it fixes the issue but according to https://github.com/ahupp/python-magic/issues/293, it has some issues related to it? 

Not sure what would be the ideal fix here.

**Comment by mahrtayyab** [comment]
https://github.com/mahrtayyab/tweety/commit/2b0167dc7760c18243c8df4e0f98ccddac96ad38
