### ISSUE TITLE
iter_list_member with await

### ISSUE THREAD

**Issue by HamedAkhavan** [mahrtayyab/tweety#232]
Hi, 
I'm running iter_list_member and my code is not async and I get the following error:

> File "/usr/local/lib/python3.10/site-packages/tweety/__init__.py", line 21, in wrapper
    return loop.run_until_complete(coro)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/tweety/utils.py", line 73, in wrapper
    return await func(self, *args, **kwargs)
TypeError: object async_generator can't be used in 'await' expression

tweety version: 2.0.6 from pypi

**Comment by mahrtayyab** [comment]
can you please post your code snippet

**Comment by HamedAkhavan** [comment]
@mahrtayyab this is my code:
```python
proxy_ = get_proxy()
proxy = Proxy(
    host=proxy_["host"],
    port=proxy_["port"],
    proxy_type=PROXY_TYPE_SOCKS5,
    username=proxy_["username"],
    password=proxy_["password"],
)
app = Twitter(scraper_account.username, proxy=proxy)
app.sign_in(
	scraper_account.username,
	scraper_account.password,
	extra={
	    "enter_phone": scraper_account.phone,
	    "enter_text": scraper_account.phone,
	},
)
app.iter_list_member("220100704", 10000)
```

**Comment by mahrtayyab** [comment]
https://github.com/mahrtayyab/tweety/issues/223#issuecomment-2495796328

**Comment by mahrtayyab** [comment]
You can use `get_list_member`

**Comment by HamedAkhavan** [comment]
@mahrtayyab thanks, but how to get one page at a time instead of getting all pages using `get_list_member`?
