### ISSUE TITLE
Still Failed to Locate `libmagic` on Windows

### ISSUE THREAD

**Issue by Yuuzi261** [mahrtayyab/tweety#233]
## Problem Statement

This issue occurs specifically on Windows environments.

When using `tweety-ns==2.0.7` as specified in `requirements.txt`, the following issue occurs:

### Steps to Reproduce

1. Install dependencies using:
   ```bash
   pip install -r requirements.txt
   ```
2. Run the provided test code:
   ```python
   from tweety import Twitter
   import asyncio

   async def main():
       app = Twitter("session")
       await app.load_auth_token('abcdefghijklmnopqrstuvwxyz123456789abcde')
       print(app.me)

   asyncio.run(main())
   ```

### Observed Behavior

The installation and execution fail with the following traceback:

```plaintext
Traceback (most recent call last):
  File "D:\GitHub\Yuuzi\Tweetcord\temp.py", line 1, in <module>
    from tweety import Twitter
  File "C:\Users\Yuuzi\miniconda3\envs\temp\Lib\site-packages\tweety\__init__.py", line 6, in <module>
    from .bot import BotMethods
  File "C:\Users\Yuuzi\miniconda3\envs\temp\Lib\site-packages\tweety\bot.py", line 4, in <module>
    from .utils import (find_objects, AuthRequired, get_user_from_typehead, get_tweet_id, check_translation_lang,
  File "C:\Users\Yuuzi\miniconda3\envs\temp\Lib\site-packages\tweety\utils.py", line 12, in <module>
    import magic
  File "C:\Users\Yuuzi\miniconda3\envs\temp\Lib\site-packages\magic\__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Yuuzi\miniconda3\envs\temp\Lib\site-packages\magic\loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

### Expected Behavior

The script should execute without errors and produce output similar to:

```plaintext
User(id=xxxxxxxxxxxxxxxxxxx, username=xxx, name=xxx, verified=False)
```

## Workaround

By explicitly installing `magic-python` before installing the dependencies in `requirements.txt`, the issue can be resolved:

```bash
pip install magic-python
pip install -r requirements.txt
```

### Successful Execution Result

The script produces the correct output:

```plaintext
User(id=xxxxxxxxxxxxxxxxxxx, username=xxx, name=xxx, verified=False)
```

## Proposed Solution

Despite attempts to include `magic-python` in `requirements.txt`, this alone does not resolve the issue. Additionally, installing `tweety-ns==2.0.7` directly after `magic-python` still results in errors. For some unknown reason, the specific sequence of first installing `magic-python` and then using `pip install -r requirements.txt` appears to be the only way to avoid the error. This behavior is puzzling and requires further investigation. Input from the library's maintainers would be greatly appreciated to understand and resolve this anomaly.

**Comment by mahrtayyab** [comment]
https://github.com/mahrtayyab/tweety/commit/696f81a6e930ac18443c865d3244c305e32ffc48
