### ISSUE TITLE
how to get twitter home page " You might like" list or  "Who to follow" list

### ISSUE THREAD

**Issue by yd-mark** [mahrtayyab/tweety#235]
i want to follow users, in the home page, twitter recommends Users by "You might like" tab，is there any functions to get the list?
<img width="1325" alt="image" src="https://github.com/user-attachments/assets/ce2db70c-88cc-4d43-a5e3-498a4b098030" />

**Comment by mahrtayyab** [comment]
Not yet , will be available in next release

**Comment by yd-mark** [comment]
thanks! I'm looking forward to next release!

**Comment by mahrtayyab** [comment]
Do consider updating please.
[get_suggested_users](https://mahrtayyab.github.io/tweety_docs/basic/all-functions.html#TwitterAsync.get_suggested_users)

**Comment by yd-mark** [comment]
thanks!! it works for me after updating!

**Comment by yd-mark** [comment]
but i have a question: is there any iter function about get_suggested_users_iter?
