### ISSUE TITLE
Limited to 40 search results

### ISSUE THREAD

**Issue by adihanifsdr** [mahrtayyab/tweety#26]
Hello

I've encountered an problem where if i'm called this function
```
tweets = app.search('Elon Musk', pages=50)
```
The results should return number of pages to get until 50 page. But it only returned 40 data results. I've tried 

- pagination looping using cursor 
- call get_next_page() but return no results

None of them worked. Any other approach?

**Comment by mahrtayyab** [comment]
Try adding wait_time

**Comment by adihanifsdr** [comment]
> Try adding wait_time

Hello, @mahrtayyab, Thanks for your reply!

I've tried adding  wait_time=20 then 50, still only returning 40-44 data only.

**Comment by mahrtayyab** [comment]
Okay I found the issue , will be fixed soon

**Comment by adihanifsdr** [comment]
Hello @mahrtayyab,

Thank you for looking into this issue! I'm glad to hear that you've identified the problem. Could you please provide some more details on what the issue is and how you plan to fix it? It would be helpful to understand the underlying cause and to learn from it for future reference. I appreciate your assistance in resolving this matter

**Comment by adihanifsdr** [comment]
> Okay I found the issue , will be fixed soon


Hello @mahrtayyab ,

Thank you for looking into this issue! I'm glad to hear that you've identified the problem. Could you please provide some more details on what the issue is and how you plan to fix it? It would be helpful to understand the underlying cause and to learn from it for future reference. I appreciate your assistance in resolving this matter

**Comment by mahrtayyab** [comment]
It has been fixed , please do consider updating.

**Comment by madhukar01** [comment]
I think this issue is back? or is it just me :(

**Comment by madhukar01** [comment]
I raised a PR for the fix, check it out @mahrtayyab
