### ISSUE TITLE
get users replies and the tweet replied to

### ISSUE THREAD

**Issue by smyja** [mahrtayyab/tweety#33]
I am trying to get users replies and the tweet replied to but it isn't working
```
tweet_dict = {}
for tweet in all_tweets:
    tweet_dict[tweet_number] = {
        "text": tweet.text,
        "quoted_tweet": None,
        "replied_tweet": None,
        "user_reply": None,
        "tweet_replied_to": None
    }

    if tweet.quoted_tweet is not None:
        tweet_dict[tweet_number]["quoted_tweet"] = tweet.quoted_tweet.tweet_body

    if tweet.is_reply:
        replied_tweet = app.get_tweet(tweet.replied_to)
        tweet_dict[tweet_number]["replied_tweet"] = replied_tweet.text

        user_replies = app.get_tweets(replied_tweet.author.username, pages=1, replies=True)
        for reply in user_replies:
            if reply.replied_to == replied_tweet.id:
                tweet_dict[tweet_number]["user_reply"] = reply.text
                tweet_dict[tweet_number]["tweet_replied_to"] = replied_tweet.text
                break

    tweet_number += 1
```

i keep getting null and none for it

**Comment by Czefrej** [comment]
I have got the same issue.

**Comment by smyja** [comment]
> I have got the same issue.

currently trying out snscrape.

**Comment by mahrtayyab** [comment]
In some cases , the data returned by Twitter doesn't contain the replied_to , we have to make another http request for that (which the library isn't doing right now), it will be fixed in the next pypi release

**Comment by Bilitubbies** [comment]
![image](https://github.com/mahrtayyab/tweety/assets/60609747/355c41e2-f390-46d9-bc71-1a558af674ba)
I think if there's a need to add `is True` for evaluating `original_tweet[x]` as a Non-empty string, it doesn't make sense cuz even if it isn't empty, the result of this statement remains to be `False`, and I think it is a bug.

**Comment by muskit** [comment]
We might wanna keep this open since we're still not making an extra request to retrieve the reply_to
