### ISSUE TITLE
KeyError: 'result'

### ISSUE THREAD

**Issue by jerry199507** [mahrtayyab/tweety#34]
tweety/types/usertweet.py", line 32, in _get_tweet_content_key
    return [tweet['content']['itemContent']['tweet_results']['result']]
KeyError: 'result'
maybe it should be  return [tweet['content']['itemContent']['tweet_results'].get('result')]   ?

**Comment by mahrtayyab** [comment]
Can you please send the Tweet ID if possible

**Comment by mahrtayyab** [comment]
It is fixed , do consider upgrading
