### ISSUE TITLE
Error in Documentation for iter_tweets

### ISSUE THREAD

**Issue by adamdubsky** [mahrtayyab/tweety#39]
The example for iter_tweets is

`
app = Twitter() 
for userTweetsObj, tweet in tweets.iter_tweets('elonmusk'):
    print(tweet)
`

and it should be
`app = Twitter() 
for userTweetsObj, tweet in app.iter_tweets('elonmusk'):
    print(tweet)`

**Comment by mahrtayyab** [comment]
It is fixed
