### ISSUE TITLE
documentation/update readme to fix array reference

### ISSUE THREAD

**Issue by rm0nroe** [mahrtayyab/tweety#4]
First, thank you for referencing this repository from [twitter-scraper #197](https://github.com/bisguzar/twitter-scraper/issues/197) 

In setup, I found that you have a typo in your readme. It errors in that "tweets" is not found. See below:
```
all_tweets = app.get_tweets()
for tweet in tweets:
```

```for tweet in tweets:``` should be updated to ```for tweet in all_tweets:```

Cheers 🍻

**Comment by mahrtayyab** [comment]
Thank you so much , it is fixed now.
