### ISSUE TITLE
Limit tweets for each page

### ISSUE THREAD

**Issue by kairusds** [mahrtayyab/tweety#40]
I'm not sure why but for every page, the amount of maximum tweets retrieved seems to be random.

**Comment by bengabp** [comment]
Ive experienced this myself, but I dont think its an issue, The twitter frontend api does not return consistend data, it varies between ± 2 or 3 results

**Comment by mahrtayyab** [comment]
> Ive experienced this myself, but I dont think its an issue, The twitter frontend api does not return consistend data, it varies between ± 2 or 3 results

Can you please send the username of the concerned user .

**Comment by bengabp** [comment]
@mahrtayyab I am not sure if i understand what you mean. Could you please rephrase?

**Comment by mahrtayyab** [comment]
> @mahrtayyab I am not sure if i understand what you mean. Could you please rephrase?

You are trying to get the tweets of a user through which you come to know that there are an inconsistent number of tweets on each page , can you please share the username of that user

**Comment by bengabp** [comment]
@mahrtayyab you do not understand what i was trying to say. I said i once used the twitter frontend api directly (without this library) and for each pagination i get like 22 tweets and for the next page i get like 23 or 20 tweets, so i was trying to say that this is just something with the twitter frontend api

**Comment by mahrtayyab** [comment]
> @mahrtayyab you do not understand what i was trying to say. I said i once used the twitter frontend api directly (without this library) and for each pagination i get like 22 tweets and for the next page i get like 23 or 20 tweets, so i was trying to say that this is just something with the twitter frontend api

Yes I know what you are saying , I am saying that if you can send you an example username , I might be able to debug the issue properly , there might be some elements or property not begin parsed by the library

**Comment by bengabp** [comment]
@mahrtayyab I think it happens for any username, just search a user with lots of tweets in their timeline.

**Comment by mahrtayyab** [comment]
It is because a page of tweets also contains other things like suggested users etc which often decreases the number of tweets in a page
