### ISSUE TITLE
Initiating Twitter client causes '[38]countryCode parameter is missing' on ECS Fargate 

### ISSUE THREAD

**Issue by fahadnbs** [mahrtayyab/tweety#43]
I'm able to successfully run the application using tweety-ns on my local machine and even on docker locally. However when I try to run the docker image on an ECS Fargate cluster, it causes the following error when instantiating the Twitter client from tweety.bot:

![image](https://github.com/mahrtayyab/tweety/assets/77164998/74443cb9-8011-4864-9164-92cee83caea0)

When debugging the issue, I found out that the client initiation merely makes POST requests without passing any parameters to: 
- https://api.twitter.com/1.1/guest/activate.json
- https://twitter.com/i/api/1.1/branch/init.json

Could not find where the countryCode parameter is needed which is causing the issue on the ECS Fargate cluster. 

cc: @mahrtayyab

**Comment by mahrtayyab** [comment]
Init API was required previously , not now , try upgrading library using

`pip install https://github.com/mahrtayyab/tweety/archive/main.zip --upgrade --force-reinstall`

It was removed in later versions

**Comment by mahrtayyab** [comment]
It is fixed , do consider upgrading
