### ISSUE TITLE
Status Check

### ISSUE THREAD

**Issue by bengabp** [mahrtayyab/tweety#44]
## Is this project still alive ?
OR is this really an issue. No its not. I added 2 new features to this library and I am really excited to tell you guys, ill be making a pull request later , cos I will have to spend little time writing a note of the changes I've made. Well , not much, 

- I added feature to get the actual likes and retweets of a tweet
- Added rate limit exception class

Yes, the frontend api does have ratelimiting, but you have to make lots of request for it to be triggered which is just an edge case. So i have added a class for it incase users want to handle the exception, To trigger it you will have to make up to 25000 requests in a short amount of time.

The other feature was to solve my problem of getting the actual retweets and likes as i was working on a scraper for statistics.

**Comment by mahrtayyab** [comment]
Yes the project is alive , I was working on the client side of the project as the Twitter pushed everything behind the wall today.

**Comment by bizrockman** [comment]
thanks for your effort. Really. Before this I did scraping the side itself, what took quite a long time. This explains why I am getting 500 all the time today?

**Comment by fahadnbs** [comment]
@mahrtayyab Thanks for your effort. Is the issue fixed? I'm still getting a 500 on the latest pull

**Comment by mahrtayyab** [comment]
@fahadnbs It will be fixed in the next release schedule tomorrow, I was waiting for Twitter changes to be done first then update the library, now we are required to be logged-in in order to get any information.

**Comment by bengabp** [comment]
Great to hear that this project is still alive.
Thank you @mahrtayyab for this library, It took me 3weeks to develop a similar solution but using playwright with reusable sessions. This library makes it alot faster for me.

![Screenshot_20230701-074553.jpg](https://github.com/mahrtayyab/tweety/assets/84660669/a060134d-639a-4880-9b76-f58183769cfe)

Also Elon musk says this is temporary. Not sure what he meant but either ways, we now know this can happen and for now we'll be needing an account
