### ISSUE TITLE
get_user_info()

### ISSUE THREAD

**Issue by fabston** [mahrtayyab/tweety#48]
Hi,

I have been using the `get_user_info` endpoint a lot to grab data such as profile pic, description, on list count, followers etc.

Since the new update I am now only able to grab: `User(id=44196397, username=elonmusk, name=Elon Musk, verified=True)`. Is that to be expected? The code I used:
```py
from tweety.bot import Twitter

app = Twitter(cookies=cookies)
get_user_info = app.get_user_info("elonmusk")
```

The code I used before:
```py
from tweety.bot import Twitter

get_user_info = Twitter(username).get_user_info().to_dict()['legacy']
```

Cheers, keep up the great work.

**Comment by mahrtayyab** [comment]
This is just the representation of User class, you can access the attributes of class using dot notation , like if you want the username you can do 

```
from tweety.bot import Twitter

cookies= "cookies"
app = Twitter(cookies=cookies)
user = app.get_user_info("elonmusk")
print(user.username)
```

More about User Class [here](https://mahrtayyab.github.io/tweety_docs/basic/twDataTypes.html#User)
