### ISSUE TITLE
app.search(keyword) returns Tweet(id=None, author=None, created_on=None)

### ISSUE THREAD

**Issue by ares-osint** [mahrtayyab/tweety#51]
Hi.
Using the cookies works for app.get_user_info(username), app.get_tweets(username), app.get_trends() but not for app.search().
It gets an empty response: (Tweet(id=None, author=None, created_on=None))
Don't know if the user auth have been implemented.
I'm using tweety-ns @ https://github.com/mahrtayyab/tweety/archive/main.zip
Thank you for all your efforts and contributions.

**Comment by mahrtayyab** [comment]
Can you please provide steps to reproduce the issue

**Comment by ares-osint** [comment]
Script:
from tweety.bot import Twitter
from tweety.filters import SearchFilters


cookies_value = {....}

cookies = cookies_value
app = Twitter(cookies=cookies)

tweets = app.search(keyword='London',pages=1,wait_time=2,filter_='filters.SearchFilters.Latest()')
for tweet in tweets:
    print(tweet)


output:
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)
Tweet(id=None, author=None, created_on=None)

**Comment by mahrtayyab** [comment]
I have found another issue , soon will be sorted too

**Comment by andrie4ko** [comment]
Hi,
you did a great job, thanks!

Everything works well, but I also see that the search doesn't work:

```
Twitter().search(keyword: str, pages: int = 1, filter_: str = None, wait_time: int = 2, cursor: str = None)

Twitter().iter_search(keyword: str, pages: int = 1, filter_: str = None, wait_time: int = 2, cursor: str = None)
```

both of them return the correct answer, and I see the 'http' property, but can't realize where the current fields are located.
some of them under 'legacy', the 'full_text' for instance.

**Comment by mahrtayyab** [comment]
The issue has been address in latest update , please do consider upgrading
