### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by lakshmi-shravya** [mahrtayyab/tweety#52]
I used the library a few weeks ago, it was working fine but now it is coming up with an authentication error. Can anyone please help?

```
**AuthenticationRequired                    Traceback (most recent call last)
Cell In[2], line 1
----> 1 twitter_client = Twitter()
      3 tweets = twitter_client.get_tweets("saylor")
      5 df = create_dataframe_from_tweets(tweets)

File ~\anaconda3\lib\site-packages\tweety\bot.py:39, in Twitter.__init__(self, max_retires, proxy, cookies)
     30 """
     31 Constructor of the Twitter Public class
     32 
   (...)
     35 :param cookies: (`str` or `dict`) Cookies which will be used for user authentication
     36 """
     38 if not cookies:
---> 39     raise AuthenticationRequired(200, "GenericForbidden", None)
     41 self.request = Request(max_retries=max_retires, proxy=proxy, cookies=cookies)
     42 self.user = self.get_user_info()

AuthenticationRequired: You need to be authenticated to make this request**
```

**Comment by mahrtayyab** [comment]
Now twitter requires the user to be logged in in order to get tweets , please do check docs for more details

**Comment by pduggi-cf** [comment]
Hello love the library!

When you say cookies what should I be using and what's the format for the cookies, adding that would be super useful

I

**Comment by lakshmi-shravya** [comment]
I used the token from the browser directly, so 

app = Twitter(cookies='cookieFromBrowser')

there is an example here --> [https://mahrtayyab.github.io/tweety_docs/basic/quick-start.html](url)

**Comment by bocxx** [comment]
Same issue.  Can anyone provide a working code? Just for demo?

**Comment by bocxx** [comment]
Sorry this is the error I got: Traceback (most recent call last):
  File "/Users/blabla/Projects/App/tweet.py", line 3, in <module>
    app = Twitter(cookies=cookies)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blabla/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tweety/bot.py", line 41, in __init__
    self.request = Request(max_retries=max_retires, proxy=proxy, cookies=cookies)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nblabla/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tweety/http.py", line 18, in __init__
    self.__session = s.Client(proxies=proxy, cookies=self._parse_cookies(cookies), timeout=60)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blabla/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tweety/http.py", line 67, in _parse_cookies
    raise InvalidCredentials(None, None, None, "'ct0' key in cookies isn't available")
tweety.exceptions_.InvalidCredentials: 'ct0' key in cookies isn't available

**Comment by mahrtayyab** [comment]
> Sorry this is the error I got: Traceback (most recent call last):
>   File "/Users/blabla/Projects/App/tweet.py", line 3, in <module>
>     app = Twitter(cookies=cookies)
>           ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/blabla/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tweety/bot.py", line 41, in __init__
>     self.request = Request(max_retries=max_retires, proxy=proxy, cookies=cookies)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/nblabla/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tweety/http.py", line 18, in __init__
>     self.__session = s.Client(proxies=proxy, cookies=self._parse_cookies(cookies), timeout=60)
>                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/blabla/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tweety/http.py", line 67, in _parse_cookies
>     raise InvalidCredentials(None, None, None, "'ct0' key in cookies isn't available")
> tweety.exceptions_.InvalidCredentials: 'ct0' key in cookies isn't available

You are passing incomplete cookies

**Comment by mahrtayyab** [comment]
![image](https://github.com/mahrtayyab/tweety/assets/38404705/5ccaa1ac-f0b8-4928-8496-188a92e866c5)
Soon the update with login support will be released.

**Comment by josephnk23** [comment]
> ![image](https://user-images.githubusercontent.com/38404705/253315091-5ccaa1ac-f0b8-4928-8496-188a92e866c5.png) Soon the update with login support will be released.

will I be able to get the tweet urls?

**Comment by bocxx** [comment]
Thank you for the reply! With some help of Claude I managed to parse the cookies the right way! Tnx again!

**Comment by mahrtayyab** [comment]
> > ![image](https://user-images.githubusercontent.com/38404705/253315091-5ccaa1ac-f0b8-4928-8496-188a92e866c5.png) Soon the update with login support will be released.
> 
> will I be able to get the tweet urls?

You can construct it yourself
tweet_url = f"https://twitter.com/{tweet.author.username}/{tweet.id}"

**Comment by mahrtayyab** [comment]
New Sign in method has been added to address this issue , please do consider upgrading
