### ISSUE TITLE
session.json directory

### ISSUE THREAD

**Issue by nballen-tx** [mahrtayyab/tweety#54]
Hi,

Is that possible to have the session.json to be save in a particular folder instead of the current directory.

Thanks,

**Comment by mahrtayyab** [comment]
It will be added in next release

**Comment by mahrtayyab** [comment]
Added in latest release , do consider upgrading

**Comment by nballen-tx** [comment]
thank you mahrtayyab

**Comment by nballen-tx** [comment]
Tried to find the details, but struggled to get.

Do you mind giving me an example of how the json path would work now please?

Thanks,

**Comment by dgw** [comment]
I looked in the code to figure it out earlier. Pass a path as the session name and the library will split off a folder name later. Like:

```py
app = Twitter("/path/to/session-name")
```

(If I'm wrong, I'll find out soon when I try to test my updated downstream code…)

**Comment by mahrtayyab** [comment]
> I looked in the code to figure it out earlier. Pass a path as the session name and the library will split off a folder name later. Like:
> 
> ```python
> app = Twitter("/path/to/session-name")
> ```
> 
> (If I'm wrong, I'll find out soon when I try to test my updated downstream code…)

@nballen-tx yes
