### ISSUE TITLE
Pagination on Twitter().search() doesn't work

### ISSUE THREAD

**Issue by andrie4ko** [mahrtayyab/tweety#55]
The function Twitter().search() always returns only first page
 
Argument "pages=1",  and "pages=10" in the example

```
tweets = app.search('elonmusk')
for tweet in tweets:
    print(tweet)
```

return tweets from the first page only.

**Comment by dgw** [comment]
#26 / #53

**Comment by mahrtayyab** [comment]
Closing in favour of #26 , upgrade to latest version using ``pip install https://github.com/mahrtayyab/tweety/archive/main.zip --upgrade ``
