### ISSUE TITLE
Donation 

### ISSUE THREAD

**Issue by Allen-Taylor** [mahrtayyab/tweety#56]
I'm using this for a project and I'd like to donate to you. 

Can you please put up a donation link?

Also, has anyone reported any issues with accounts being banned when using this library?

**Comment by mahrtayyab** [comment]
Thank you for appreciation , you can donate at https://www.buymeacoffee.com/mahrtayyab

Further , no one has reported the banning of account using Tweety. I will suggest to use enough delay using sleep function between actions to be on safer side.

Thank you again
