### ISSUE TITLE
Unknown Error Occurs on Twitter when requesting a Tweet Detail

### ISSUE THREAD

**Issue by nainiayoub** [mahrtayyab/tweety#60]
I am trying to get tweet details, however it is not working. It keeps giving me `UnknownError: Unknown Error Occurs on Twitter`.

Any suggestions?

```Python
from tweety import Twitter

app = Twitter("session")
tweet = app.tweet_detail("https://twitter.com/Microsoft/status/1442542812197801985")
```

**Comment by dgw** [comment]
You should read the docs. Signing in is required. https://mahrtayyab.github.io/tweety_docs/basic/singing-in.html

**Comment by mahrtayyab** [comment]
> I am trying to get tweet details, however it is not working. It keeps giving me `UnknownError: Unknown Error Occurs on Twitter`.
> 
> Any suggestions?
> 
> ```python
> from tweety import Twitter
> 
> app = Twitter("session")
> tweet = app.tweet_detail("https://twitter.com/Microsoft/status/1442542812197801985")
> ```

You should be logged in 
![image](https://github.com/mahrtayyab/tweety/assets/38404705/df30ca0b-9ee6-4277-beb2-3d9f560f99c5)

**Comment by dgw** [comment]
(Note that the `connect()` method only works once a session has been established and saved using either `sign_in(user, pass)` or `load_cookies(cookie_string)`.)
