### ISSUE TITLE
Asynchronous get_tweets

### ISSUE THREAD

**Issue by woncoh1** [mahrtayyab/tweety#62]
Hi, thanks for this wonderful library. Given the current Musk-induced Twitter API disaster, this library seems to be the only asylum.

1. I was wondering whether you have plans for an async version of get_tweets (https://mahrtayyab.github.io/tweety_docs/basic/all-functions.html#get-tweets). httpx seems to support both sync and async, so I was hoping you can add async in the near future.

2. I am trying to listen to the latest tweet updates from selected Twitter users, but the Twitter.get_tweets function returns different contents depending on whether you are logged in. Why do I only get the latest tweets when I log in? If I log in and call get_tweets frequently, say every 5 seconds, wouldn't this expose my Twitter account to be banned?

Thanks.

**Comment by mahrtayyab** [comment]
1. Yes async version is underdevelopment.

2. Twitter rate limits are messing up everything, + if you could send the username of the user you trying to get tweets of , I would be able to debug things more efficiently. 

About banning , always take precautionary measure , although chances of  getting banned are too little.

**Comment by rmc135** [comment]
> 2\. In Google Colab, I tried the non-login version in the "A quick example:" section of the repo README:
...
> The output seemed to be randomly sampled starting from 2018:

I believe this was changed when Twitter first disallowed views by unauthenticated users, then after some fallout changed it back. As you have noted, the posts are not ordered by time, but rather by likes, or perhaps views, rather than chronologically. I looked at the first 3 posts returned in the list above and they have 4.6M, 3.1M, and 2.5M likes respectively.

I don't know of a way to force the order, but I hope this explains why the list is seemingly random.

**Comment by mahrtayyab** [comment]
Yes when not authenticated , the tweets are by default sorted according to the number likes.

**Comment by woncoh1** [comment]
Thanks to both of you.
Can we change the default sorting of un-authenticated get_tweet as reverse chronological?

**Comment by woncoh1** [comment]
Never mind. I solved both the async and reverse chronological problems.

**Comment by prog-mlml** [comment]
@woncoh1 , can you share how did you solve the problem?
thanks

**Comment by mahrtayyab** [comment]
@woncoh1  how did you solved this sorting problem
