### ISSUE TITLE
Python 3.8 not supported

### ISSUE THREAD

**Issue by dgw** [mahrtayyab/tweety#63]
The project's README says that `tweety` requires Python 3.6+; however, there is at least one usage of the `|` operator (in [PEP 604](https://www.python.org/dev/peps/pep-0604) style) that won't work on Python<3.10:

```
[...]
  File "/home/dgw/.local/lib/python3.8/site-packages/tweety/utils.py", line 106, in <module>
    def find_object(obj: dict, fn: Callable[[dict], bool]) -> Any | None:
TypeError: unsupported operand type(s) for |: '_SpecialForm' and 'NoneType'
```

To maintain compatibility with older Python versions, this kind of type annotation can be written using [`typing.Union`](https://docs.python.org/3/library/typing.html#typing.Union) instead. Otherwise, the only action needed to "fix" this issue is updating the library's documented Python version support.

**Comment by mahrtayyab** [comment]
Thank you for pointing out , fixed in latest release
