### ISSUE TITLE
I am getting only 100 results

### ISSUE THREAD

**Issue by Nagaraj4896** [mahrtayyab/tweety#66]
For get tweets, i am getting only 100 results, i need more than that upto latest tweet, how can we do that
```
from tweety import Twitter

app = Twitter("session")

username = "elonmusk"

all_tweets = app.get_tweets(username)```

**Comment by mw3i** [comment]
I think you can just do app.get_next_page()

**Comment by mahrtayyab** [comment]
You can specify the `pages` argument

**Comment by mahrtayyab** [comment]
Also make sure you are signed in
