### ISSUE TITLE
tweet.card:  Card without choices throws: 'NoneType' has no len()

### ISSUE THREAD

**Issue by thomasf1** [mahrtayyab/tweety#7]
Just started, yet getting some error when trying to access tweet.card that has no choices:

`
Traceback (most recent call last):
  File "/Users/tom/Dev/test/gayTwitter/guys.py", line 20, in <module>
    print(tweet.card)
  File "/opt/homebrew/lib/python3.10/site-packages/tweety/types/twDataTypes.py", line 610, in __repr__
    return f"Card(id={self.rest_id}, choices={len(self.choices) if self.choices else []}, end_time={self.end_time}, duration={len(self.duration)} minutes)"
TypeError: object of type 'NoneType' has no len()
`

**Comment by mahrtayyab** [comment]
Can you please share the tweet link you are trying ?

**Comment by thomasf1** [comment]
I´m just debugging it now, seems not the choices are the issue, the duration is None. Thanks for your quick response, give me a few min :)

**Comment by thomasf1** [comment]
So, it turns out they use the Card to link somewhere and the class Card in __parse_choices is looking for choice, end, last, duration but it gets none of them.

__parse_choices
['thumbnail', 'image']
['description']
['domain']
['thumbnail', 'image', 'large']
['thumbnail', 'image', 'original']
['thumbnail', 'image', 'small']
['thumbnail', 'image', 'x', 'large']
['vanity', 'url']
['thumbnail', 'image', 'color']
['title']
['card', 'url']

therefore, no duration is updated.

**Comment by thomasf1** [comment]
I guess the best way to handle this might be to check if the card has choices and otherwise treat is as a link

**Comment by mahrtayyab** [comment]
Do you have any example tweet link? Can you please link it , so I can check it and update accordingly

**Comment by thomasf1** [comment]
for now, just doing `{len(self.duration) if self.duration else ''}` fixes it for me.

return f"Card(id={self.rest_id}, choices={len(self.choices) if self.choices else []}, end_time={self.end_time}, duration={len(self.duration) if self.duration else ''} minutes)"

**Comment by mahrtayyab** [comment]
It is fixed in new update 1.0.1, update using pip
pip3 install tweety-ns --upgrade
