### ISSUE TITLE
how to get all the tweets wrt to a userid; i am getting only limited number of tweets

### ISSUE THREAD

**Issue by harshithagolla** [mahrtayyab/tweety#70]
this is the code i used to get the tweets based on the userid and copied them to a csv file. but im getting only limited number of tweets . can someone provide me a sample code as it would be really helpful.

from tweety import Twitter
import csv
import os

app = Twitter("session")
app.sign_in("", "")
target_username = ""

user = app.get_user_info(target_username)
all_tweets = app.get_tweets(user)

csv_filename = ""
csv_exists = os.path.exists(csv_filename)

with open(csv_filename, mode='a', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)

    if not csv_exists:
        writer.writerow(["Tweet ID", "Username", "Tweet Text", "Created On"])  # Write header if file is new

    for tweet in all_tweets:
        writer.writerow([tweet.id, tweet.author.username, tweet.text, tweet.created_on])

print("Tweets saved to CSV file.")

**Comment by mahrtayyab** [comment]
specfiy `pages` parameter to get multiple pages , 

More about [get_tweets](https://mahrtayyab.github.io/tweety_docs/basic/all-functions.html#get-tweets)

**Comment by 2manov** [comment]
`pages` doesn't work. I always get 100 random tweets by username, but I can't understand take only last 100 tweets or more

**Comment by harshithagolla** [comment]
**using pages gives me an error**

from tweety import Twitter

app = Twitter("session")
app.sign_in("", "")
target_username = ""

user = app.get_user_info(target_username)

# Define the number of pages you want to fetch
num_pages = 5

all_tweets = []
for page in range(1, num_pages + 1):
    page_tweets = app.get_tweets(user, pages=page)
    all_tweets.extend(page_tweets)

for tweet in all_tweets:
    print(tweet.text)



---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
Input In [12], in <cell line: 13>()
     12 all_tweets = []
     13 for page in range(1, num_pages + 1):
---> 14     page_tweets = app.get_tweets(user, pages=page)
     15     all_tweets.extend(page_tweets)
     17 for tweet in all_tweets:

File ~\anaconda3\lib\site-packages\tweety\bot.py:98, in BotMethods.get_tweets(self, username, pages, replies, wait_time, cursor)
     94 user_id = self._get_user_id(username)
     96 userTweets = UserTweets(user_id, self.request, pages, replies, wait_time, cursor)
---> 98 results = list(userTweets.generator())
    100 return userTweets

File ~\anaconda3\lib\site-packages\tweety\types\base.py:23, in BaseGeneratorClass.generator(self)
     21 def generator(self):
     22     for page in range(1, int(self.pages) + 1):
---> 23         results = self.get_next_page()
     25         yield self, results
     27         if not self.is_next_page:

File ~\anaconda3\lib\site-packages\tweety\types\usertweet.py:44, in UserTweets.get_next_page(self)
     42 _tweets = []
     43 if self.is_next_page:
---> 44     response = self.http.get_tweets(self.user_id, replies=self.get_replies, cursor=self.cursor)
     46     if not response['data']['user'].get("result"):
     47         raise UserNotFound(error_code=50, error_name="GenericUserNotFound", response=response)

File ~\anaconda3\lib\site-packages\tweety\http.py:104, in Request.get_tweets(self, user_id, replies, cursor)
    102 def get_tweets(self, user_id, replies=False, cursor=None):
    103     request_data = self.__builder.user_tweets(user_id=user_id, replies=replies, cursor=cursor)
--> 104     response = self.__get_response__(**request_data)
    105     return response

File ~\anaconda3\lib\site-packages\tweety\http.py:39, in Request.__get_response__(self, return_raw, ignoreNoneData, **request_data)
     36     return None
     38 if not response_json:
---> 39     raise UnknownError(
     40         error_code=500,
     41         error_name="Server Error",
     42         response=response,
     43         message="Unknown Error Occurs on Twitter"
     44     )
     46 if response_json.get("errors") and not response_json.get("data"):
     47     error = response_json['errors'][0]

UnknownError: Unknown Error Occurs on Twitter

**Comment by harshithagolla** [comment]
but if I increase the number of pages then i  get an error


from tweety import Twitter

app = Twitter("session")
app.sign_in("", "")
target_username = ""

user = app.get_user_info(target_username)

num_pages = 10

all_tweets = []
for page in range(1, num_pages + 1):
    page_tweets = app.get_tweets(user, pages=page)
    all_tweets.extend(page_tweets)

for tweet in all_tweets:
    print(tweet.text)
    
  
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
Input In [3], in <cell line: 13>()
     12 all_tweets = []
     13 for page in range(1, num_pages + 1):
---> 14     page_tweets = app.get_tweets(user, pages=page)
     15     all_tweets.extend(page_tweets)
     17 for tweet in all_tweets:

File ~\anaconda3\lib\site-packages\tweety\bot.py:98, in BotMethods.get_tweets(self, username, pages, replies, wait_time, cursor)
     94 user_id = self._get_user_id(username)
     96 userTweets = UserTweets(user_id, self.request, pages, replies, wait_time, cursor)
---> 98 results = list(userTweets.generator())
    100 return userTweets

File ~\anaconda3\lib\site-packages\tweety\types\base.py:23, in BaseGeneratorClass.generator(self)
     21 def generator(self):
     22     for page in range(1, int(self.pages) + 1):
---> 23         results = self.get_next_page()
     25         yield self, results
     27         if not self.is_next_page:

File ~\anaconda3\lib\site-packages\tweety\types\usertweet.py:44, in UserTweets.get_next_page(self)
     42 _tweets = []
     43 if self.is_next_page:
---> 44     response = self.http.get_tweets(self.user_id, replies=self.get_replies, cursor=self.cursor)
     46     if not response['data']['user'].get("result"):
     47         raise UserNotFound(error_code=50, error_name="GenericUserNotFound", response=response)

File ~\anaconda3\lib\site-packages\tweety\http.py:104, in Request.get_tweets(self, user_id, replies, cursor)
    102 def get_tweets(self, user_id, replies=False, cursor=None):
    103     request_data = self.__builder.user_tweets(user_id=user_id, replies=replies, cursor=cursor)
--> 104     response = self.__get_response__(**request_data)
    105     return response

File ~\anaconda3\lib\site-packages\tweety\http.py:39, in Request.__get_response__(self, return_raw, ignoreNoneData, **request_data)
     36     return None
     38 if not response_json:
---> 39     raise UnknownError(
     40         error_code=500,
     41         error_name="Server Error",
     42         response=response,
     43         message="Unknown Error Occurs on Twitter"
     44     )
     46 if response_json.get("errors") and not response_json.get("data"):
     47     error = response_json['errors'][0]

UnknownError: Unknown Error Occurs on Twitter

**Comment by harshithagolla** [comment]
can you please help me out with a clear code because im getting this error. Really sorry for the inconvenience.

from tweety import Twitter

app = Twitter("session")
app.sign_in("", "")
target_username = ""

user = app.get_user_info(target_username, pages=10)
all_tweets = app.get_tweets(user)

for tweet in all_tweets:
    print(tweet.text)


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
---> 27 user = app.get_user_info(target_username, pages=10)
     28 all_tweets = app.get_tweets(user)
     30 for tweet in all_tweets:

TypeError: get_user_info() got an unexpected keyword argument 'pages'

**Comment by mahrtayyab** [comment]
There was a typo in the last message , it is fixed

**Comment by harshithagolla** [comment]
from tweety import Twitter

app = Twitter("session")
app.sign_in("", "")
target_username = ""

user = app.get_user_info(target_username)
all_tweets = app.get_tweets(user, pages = 10)

for tweet in all_tweets:
    print(tweet.text)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [6], in <cell line: 30>()
     28 all_tweets = app.get_tweets(user, pages = 10)
     30 for tweet in all_tweets:
---> 31     print(tweet.text)

AttributeError: 'TweetThread' object has no attribute 'text'
