### ISSUE TITLE
reply to user who mentioned you in their tweet

### ISSUE THREAD

**Issue by LexiestLeszek** [mahrtayyab/tweety#72]
Hi! Awesome library, thanks a lot for it!

I am trying to figure out how to create a tweet to reply to user who mentioned me in their tweet. I didn't find it in the library itself. Any ideas?

**Comment by mahrtayyab** [comment]
`create_tweet` method accepts the optional `reply_to` parameter , you can give it a try. but make sure you are on latest github source

**Comment by LexiestLeszek** [comment]
Yes, but how exactly do I answer to the exact tweet in which the person who mentioned me?

Sorry, I'm a newbie developer.

**Comment by dgw** [comment]
Pass the ID (as string) of the tweet you want to reply to.

**Comment by mahrtayyab** [comment]
Or the tweet instance as whole

**Comment by LexiestLeszek** [comment]
but get_mentions() only returns user_id, i cannot figure out how to find the exact tweet i was mentioned in

**Comment by dgw** [comment]
> but get_mentions() only returns user_id

It returns a `Mention` object, which contains [a list of `tweets`](https://github.com/mahrtayyab/tweety/blob/31010ca9fac919b656e4d51200662e9187c56bda/src/tweety/types/mentions.py#L8).

**Comment by mahrtayyab** [comment]
Assuming `client` is the `Twitter` Class instance

``` 
mentions = client.get_mentions()
tweet = mentions[0]
client.create_tweet("Reply test", reply_to=tweet))

```

**Comment by LexiestLeszek** [comment]
@mahrtayyab hi! I used your example and got:
ine 48, in __getitem__
    return self.tweets[index]
IndexError: list index out of range

but i definetely have at least one mention

**Comment by mahrtayyab** [comment]
You are not on latest source, please uninstall tweety-ns using pip and then install it again using `pip install https://github.com/mahrtayyab/tweety/archive/main.zip --upgrade `

**Comment by LexiestLeszek** [comment]
Got it! It works, but it doesn't return all mentions for some reason. What could the problem be?

**Comment by mahrtayyab** [comment]
you can get the multiple pages by passing a page number as argument to `pages`

More about [Mentions](https://mahrtayyab.github.io/tweety_docs/basic/all-functions.html#getting-mentioned-tweets)

**Comment by LexiestLeszek** [comment]
yes it works, thanks!
