### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by bayuezha** [mahrtayyab/tweety#78]
Helllo mahrtayyab,

  I am testing the quick example and got the error below, could you please help to check? Thanks in advance!
Traceback (most recent call last):
  File "D:\PyProjects\tweety\main.py", line 1, in <module>
    from tweety import Twitter
  File "D:\PyProjects\tweety\venv\lib\site-packages\tweety\__init__.py", line 7, in <module>
    from .user import UserMethods
  File "D:\PyProjects\tweety\venv\lib\site-packages\tweety\user.py", line 8, in <module>
    class UserMethods:
  File "D:\PyProjects\tweety\venv\lib\site-packages\tweety\user.py", line 154, in UserMethods
    files: list[Union[str, UploadedMedia, tuple[str, str]]] = None,
TypeError: 'type' object is not subscriptable

**Comment by bayuezha** [comment]
Hi,
 I updated python 3.8 to the latest 3.11, it works now.

**Comment by dgw** [comment]
Yes, this kind of type annotation is not supported in Python 3.8 without `from __future__ import annotations`.

Upgrading is the workaround. However, I hope @mahrtayyab will consider modifying the claimed Python version support in the README for the next release. Supporting Python 3.6 is completely impossible with this kind of type-hint in the code, and 3.7 is EOL anyway. (Supporting 3.8 still requires the future import in affected files.)

**Comment by bayuezha** [comment]
Thanks dgw.
And I got new exeception as follows when I get tweet_detail with tweet_id which I can see from chrome.

Traceback (most recent call last):
  File "D:\PyProjects\tweety\venv\Lib\site-packages\tweety\bot.py", line 237, in tweet_detail
    raw_tweet = entry['content']['itemContent']['tweet_results']['result']['tweet']
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'tweet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyProjects\tweety\main.py", line 9, in <module>
    tweet = app.tweet_detail("1697493334309155087")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProjects\tweety\venv\Lib\site-packages\tweety\bot.py", line 242, in tweet_detail
    raise InvalidTweetIdentifier(144, "StatusNotFound", r)
tweety.exceptions_.InvalidTweetIdentifier: The Tweet Identifier is Invalid

**Comment by mahrtayyab** [comment]
Do consider upgrading

**Comment by bayuezha** [comment]
Yes, I upgraded this morning  as your suggestion like below, shall i update once more?  thanks. 

  pip install https://github.com/mahrtayyab/tweety/archive/main.zip --upgrade

**Comment by bayuezha** [comment]
I works as well after I upgraded just now, thank very much.
