### ISSUE TITLE
itemContent not found whilst scraping comments ( Common problem )

### ISSUE THREAD

**Issue by AdonisCodes** [mahrtayyab/tweety#79]
![image](https://github.com/mahrtayyab/tweety/assets/122154257/8a31921b-176b-46fd-aec9-651510c7d898)

I have had a similar problem to this whilst trying to scrape it using plain browser requests, getting the comments are extremely difficult. Hope it gets fixed soon.

**Comment by mahrtayyab** [comment]
It is fixed , the update is ready , working on docs and pypi release

**Comment by AdonisCodes** [comment]
Thanks!

**Comment by AdonisCodes** [comment]
@mahrtayyab So I should install via git currently?
Whilst you writing the new docs?

Thanks!

**Comment by mahrtayyab** [comment]
You can update now , please do check documentation first
