### ISSUE TITLE
Get quoted tweet

### ISSUE THREAD

**Issue by narodnik** [mahrtayyab/tweety#8]
I can see how to get the retweet posts, but the API seems to have no way of getting quoted tweets.
```python
    tweets_iter = Twitter(nickname).get_tweets()
    for post in tweets_iter:
        msg = post.tweet_body
        timest = post.created_on
        print(post.is_retweet, post.author.screen_name, msg, post.threads)
```

Even this code will display the person who retweeted the post when is_retweet is True, but not the original poster.

**Comment by mahrtayyab** [comment]
Thank you for pointing out , it will be included in next update

**Comment by narodnik** [comment]
Thanks a lot sir
