### ISSUE TITLE
Could I add a couple of features to the get_comments? ( Really good suggestion )

### ISSUE THREAD

**Issue by AdonisCodes** [mahrtayyab/tweety#81]
Could I add the following features:
- Verbose mode for getting comments ( Type Bool, Default = False ) It just prints after every page it collected that it collected page X
- Random Wait time ( Type Tuple with StartTime & EndTime of type int ) Default is 2 & it can switch between both types.

**Comment by mahrtayyab** [comment]
Sure

**Comment by AdonisCodes** [comment]
Thanks.
I will continue also helping on this project as I actually need something that works lol ( All the other libraries are broken )

I will be contributing the "easy" but essential stuff that I need & think others need as well.

Thanks!

**Comment by AdonisCodes** [comment]
I am also gonna add another param to the stuff that scrapes multiple pages ( Just to make sure that you still get like 70% of the results when you run into a ratelimit error ) Instead of losing like 1000 tweets. ( And I will document it )

**Comment by mahrtayyab** [comment]
> I am also gonna add another param to the stuff that scrapes multiple pages ( Just to make sure that you still get like 70% of the results when you run into a ratelimit error ) Instead of losing like 1000 tweets. ( And I will document it )

`iter_comments` is already there

**Comment by AdonisCodes** [comment]
should've read the docs lol.
Will then only add the waiting time tuple params ( int or tuple ) Int is fixed time tuple is random time.

**Comment by mahrtayyab** [comment]
instead of verbose mode , I am working on logger

**Comment by mahrtayyab** [comment]
It is added , do consider upgrading using github source.
