### ISSUE TITLE
How to get image url of webp?

### ISSUE THREAD

**Issue by bayuezha** [mahrtayyab/tweety#84]
Hello,
    I am trying to get image url with media.direct_url like below, but can only get the  photo type jpg, how can I get the url of the format webp ?
`
        _if tweet.media:
            for m in tweet.media:
                print("direct_url=" + m.direct_url)
                print("type=" + m.type)_

`

For example, in the tweet 'https://twitter.com/BBCNews/status/1698143652994752820', I can  see img src of webp ’https://pbs.twimg.com/card_img/1698143654873808896/US9sKPJm?format=webp&amp;name=small‘, how can I get it?

**Comment by mahrtayyab** [comment]
This is the URL's `twitter:image:src` meta tag value image , you can find it as
`tweet._raw['card']['legacy']['binding_values'][0]['value']['image_value']['url]`

**Comment by bayuezha** [comment]
tweet._raw doesn't work, tweet_tweet is okay, thanks a lot.
And how about media (not card) src like follows?

src="https://pbs.twimg.com/media/F315MBEWAAEvJ3_?format=jpg&amp;name=900x900" in the tweet https://twitter.com/Microsoft/status/1697285620727415264

**Comment by mahrtayyab** [comment]
> tweet._raw doesn't work, tweet._tweet is okay, thanks a lot. And how about media (not card) src like follows?
> 
> src="https://pbs.twimg.com/media/F315MBEWAAEvJ3_?format=jpg&amp;name=900x900" in the tweet https://twitter.com/Microsoft/status/1697285620727415264

This is the card too

**Comment by bayuezha** [comment]
I am now  debuging  and can not find the image_value, by the way the image is background-image:

`
<div aria-label="Three student sit at desk and work on tablets. " class="css-1dbjc4n r-1p0dtai r-1mlwlqe r-1d2f490 r-11wrixw r-61z16t r-1udh08x r-u8s1d r-zchlnj r-ipm5af r-417010" style="margin-bottom: 0px; margin-top: 0px;"><div class="css-1dbjc4n r-1niwhzg r-vvn4in r-u6sd8q r-4gszlv r-1p0dtai r-1pi2tsx r-1d2f490 r-u8s1d r-zchlnj r-ipm5af r-13qz1uu r-1wyyakw" style="background-image: url(&quot;https://pbs.twimg.com/media/F315MBEWAAEvJ3_?format=jpg&amp;name=900x900&quot;);"></div><img alt="Three student sit at desk and work on tablets. " draggable="true" src="https://pbs.twimg.com/media/F315MBEWAAEvJ3_?format=jpg&amp;name=900x900" class="css-9pa8cd"></div>
`

**Comment by bayuezha** [comment]
Hi mahrtayyab,


  Yes, you are right, I find the url(media_url_https) in string_value of card as below, thanks again.
`
          if 'card' in tweet._tweet and 'string_value' in tweet._tweet['card']['legacy']['binding_values'][0]['value']:
            data = json.loads(tweet._tweet['card']['legacy']['binding_values'][0]['value']['string_value'])
            for value in data['media_entities'].values():
                print(value['media_url_https'])

`
