### ISSUE TITLE
I get an error in processing tweet_detail and cannot execute it.

### ISSUE THREAD

**Issue by hgleam** [mahrtayyab/tweety#85]
An error occurs on line 8 when the following is executed. How can I solve this problem?

```
from tweety import Twitter
  
app = Twitter("session")

screen_name = "elonmusk"
all_tweets = app.get_tweets(screen_name)
for tweet in all_tweets:
    tweet_detail = app.tweet_detail(tweet['id'])
    print(tweet_detail)
```

Error Description
> Traceback (most recent call last):
>   File "C:\Users\Administrator\Desktop\twitter\tweety\main.py", line 8, in <module>
>     tweet_detail = app.tweet_detail(tweet['id'])
>   File "C:\Users\Administrator\Desktop\twitter\tweety\.venv\lib\site-packages\tweety\bot.py", line 238, in tweet_detail
>     response = self.request.get_tweet_detail(tweetId)
>   File "C:\Users\Administrator\Desktop\twitter\tweety\.venv\lib\site-packages\tweety\http.py", line 120, in get_tweet_detail
>     response = self.__get_response__(**self.__builder.tweet_detail(tweetId, cursor))
>   File "C:\Users\Administrator\Desktop\twitter\tweety\.venv\lib\site-packages\tweety\http.py", line 40, in __get_response__
>     raise UnknownError(
> tweety.exceptions_.UnknownError: Unknown Error Occurs on Twitter

**Comment by mahrtayyab** [comment]
Are you authenticated?

**Comment by hgleam** [comment]
My apologies. I did not authenticate.

**Comment by mahrtayyab** [comment]
Fix : Login
