### ISSUE TITLE
Issue in the search feature

### ISSUE THREAD

**Issue by Silentboy7707** [mahrtayyab/tweety#86]
There is an issue in the feature I dont know why and the error thrown is 
<img width="295" alt="image" src="https://github.com/mahrtayyab/tweety/assets/97505764/affe15f8-cf96-4ce0-8077-ead5092e7bfa">
Please let me know how can we scrap...

**Comment by mahrtayyab** [comment]
Are you logged in?

**Comment by Silentboy7707** [comment]
yes is there any limit?

**Comment by mahrtayyab** [comment]
There is no predication of limits right now , it can get rate limit even after 10 pages , or sometime not even after 100
