### ISSUE TITLE
`User` field types can be `None`, but this isn't documented

### ISSUE THREAD

**Issue by dgw** [mahrtayyab/tweety#87]
_**No huge rush to reply;** this is an API design question that might require a bit of thought, and I'm not in a hurry._

The `User` type has a bunch of fields that are set this way, using a `self._get_key()` call:

https://github.com/mahrtayyab/tweety/blob/d2336c3eae25c985a2c46e9a1225e52190c8a9d4/src/tweety/types/twDataTypes.py#L869

`_get_key()`'s `default` parameter is `None` if not specified, which is not accounted for in—to continue the above example—[the documentation for `User.favourites_count`](https://mahrtayyab.github.io/tweety_docs/basic/twDataTypes.html#User.favourites_count), which only says it is an `int`, not indicating the possibility of `None`:

<img width="260" alt="image" src="https://github.com/mahrtayyab/tweety/assets/164140/7658f6e6-64de-41ff-ab22-a49fd61c33f9">

This same annoyance could occur for any field in the `User` object, and possibly in other types as well.

For some fields (e.g. `User.description`, currently documented as just `str`), the better fix is probably just documenting that the value could be `None`.

Other fields, like `User.favourites_count` and other related profile values (e.g. status count, media count, friends, followers, etc.) that every user has but might be zero, using `_get_key('field_name', default=0)` is likely more developer-friendly for consumers of the `tweety` library. (I also noticed that `User.protected` is `bool | None` for some reason? Maybe that could use `default=False` just for consistency, though `None` and `False` behave "the same" in most cases where the value might be used in logic.)

I'm happy to put together a basic PR setting defaults where I think it makes sense, and updating the documentation for others to indicate that they may be `None`. Let me know what you think!

**Comment by mahrtayyab** [comment]
Sure you are welcome
