### ISSUE TITLE
Get entire text from tweet from verified user

### ISSUE THREAD

**Issue by RiderBull** [mahrtayyab/tweety#89]
Hi, 
First thanks for tweety which is a huge help to get Twitter data. 

I am trying to get the text from a single tweet, but as it was written by a verified user, the text content is greater than the base number. You have to click on the "see more" link to access the full text. 

So in my code, when using .text, I only get the first lines of the tweet, not the full tweet. Is there a way to get around it? 

I looked in the documentation but did not find a thing. Thanks :)

**Comment by mahrtayyab** [comment]
Can you please send the tweet link

**Comment by RiderBull** [comment]
Sure ! 
https://twitter.com/MaxDucarteron/status/1699470037415845989

app = Twitter("session")
app.sign_in(data)
target_username = "MaxDucarteron"
tweet_detail = app.tweet_detail(tweet_id)
print(tweet_detail.text)

This is what I get: 

Astuce E-commerce multi-produits : Facilitez la navigation de vos internautes en personnalisant votre barre de recherche 🔍 

➤ Listez les recherches populaires
➤ Listez les collections populaires
➤ Proposition automatique de produits avec photos selon les termes de la…

**Comment by mahrtayyab** [comment]
For the time begin you can use it like this 
`tweet_detail._tweet['note_tweet']['note_tweet_results']['result']['text']`

It will be added in next release

**Comment by RiderBull** [comment]
It worked like a charm. Thanks for the quick fix.
