### ISSUE TITLE
tweet_detail is not working

### ISSUE THREAD

**Issue by TheRed002** [mahrtayyab/tweety#90]
tweet_detail is not working with id or url.
Here's the code snippet
```
from tweety import Twitter

app = Twitter("session")
tweet = app.tweet_detail("https://twitter.com/Microsoft/status/1442542812197801985")
print(tweet)
```

and here's there error

`> python scrap.py`

> Traceback (most recent call last):
>   File "scrap.py", line 11, in <module>
>     tweet = app.tweet_detail("https://twitter.com/Microsoft/status/1442542812197801985")
>   File "/Users/bilalfarooq/.pyenv/versions/3.8.15/lib/python3.8/site-packages/tweety/bot.py", line 238, in tweet_detail
>     response = self.request.get_tweet_detail(tweetId)
>   File "/Users/bilalfarooq/.pyenv/versions/3.8.15/lib/python3.8/site-packages/tweety/http.py", line 118, in get_tweet_detail
>     response = self.__get_response__(**self.__builder.tweet_detail(tweetId, cursor))
>   File "/Users/bilalfarooq/.pyenv/versions/3.8.15/lib/python3.8/site-packages/tweety/http.py", line 38, in __get_response__
>     raise UnknownError(
> tweety.exceptions_.UnknownError: Unknown Error Occurs on Twitter

**Comment by mahrtayyab** [comment]
Are you logged in?

**Comment by TheRed002** [comment]
I was not, that was the issue.
