### ISSUE TITLE
Get tweets from Notifications

### ISSUE THREAD

**Issue by FuseFairy** [mahrtayyab/tweety#92]
It's possible to get tweets from Notifications? Thanks

**Comment by mahrtayyab** [comment]
If you want to get the tweets the user was mentioned in you can use `get_mentions` , if you want the notifications as general , it is under-development.

**Comment by FuseFairy** [comment]
I want to get these new post notifications
![image](https://github.com/mahrtayyab/tweety/assets/78064680/e81e69ed-a7ab-4b48-b094-bef55a63ce69)
