### ISSUE TITLE
Search Filters - Interval 

### ISSUE THREAD

**Issue by GunduzYuruyen** [mahrtayyab/tweety#94]
Is it possible that you can add into search() function search interval like : start_date = "2023-07-21", end_date = "2023-07-23"

app = Twitter("session")
tweets = []
for tweet in app.search('keyword', **start_date = "2023-07-21", end_date = "2023-07-23"** ):
    tweets.append(tweet)

**Comment by mahrtayyab** [comment]
You can directly add them to your keyword like 
`{actual keyword} until:2023-07-23 since:2023-07-21`

**Comment by GunduzYuruyen** [comment]
thank you so much for your reply.

app = Twitter("session")
tweets = []
for tweet in app.search({keyword} [start_date = "2023-07-21", end_date = "2023-07-23"](until:2023-07-23 since:2023-07-21 lang:en -filter:links -filter:media') ):
tweets.append(tweet)

can you also show me how to scrape user, user name, tweet text, tweet cretation time, like counts, retweet counts, view counts.
how can i add this into my code, can you help me?

**Comment by dgw** [comment]
> can you also show me how to scrape user, user name, tweet text, tweet cretation time, like counts, retweet counts, view counts.
> how can i add this into my code, can you help me?

Please reference [the documentation](https://mahrtayyab.github.io/tweety_docs/basic/twDataTypes.html#tweet). All of the available metadata fields are listed.

**Comment by GunduzYuruyen** [comment]
I m not expert on coding, I ve check the documentation already but I couldnt it by myself thats why I asked help in here

**Comment by mahrtayyab** [comment]
> thank you so much for your reply.
> 
> app = Twitter("session") tweets = [] for tweet in app.search({keyword} [start_date = "2023-07-21", end_date = "2023-07-23"](until:2023-07-23 since:2023-07-21 lang:en -filter:links -filter:media') ): tweets.append(tweet)
> 
> can you also show me how to scrape user, user name, tweet text, tweet cretation time, like counts, retweet counts, view counts. how can i add this into my code, can you help me?

``python

client = Twitter("test")
client.connect()
print(client.me)
search = client.search("(#Pakistan) lang:en until:2023-07-23 since:2023-07-21 -filter:links -filter:replies")
for tweet in search:
    print(f"Tweet Text : {tweet.text}")
    print(f"Author : {tweet.author.username}")
    print(f"Tweet Creation Date : {tweet.date}")
    print(f"Tweet Likes : {tweet.likes}")
    print(f"Tweet Retweets : {tweet.retweet_counts}")
    print(f"Tweet Views : {tweet.views}")

``

**Comment by GunduzYuruyen** [comment]
Thank you so much for your patience, kindness, understanding and attitude.
