### ISSUE TITLE
Media object type attribute does not match documentation

### ISSUE THREAD

**Issue by Yuuzi261** [mahrtayyab/tweety#95]
I found a discrepancy between the documentation and the actual behavior of the Media object in tweety. According to the documentation, the type attribute of a Media object should return either `video` or `image`, depending on the media type. 
However, when I tested it with some tweets, I found that it returns `video` or `photo` instead. 

screenshot from documentation :
![image](https://github.com/mahrtayyab/tweety/assets/63157008/d163222f-deee-4e6c-a187-ea404c34f994)
screenshot from test result :
![image](https://github.com/mahrtayyab/tweety/assets/63157008/6966f2b5-2915-4533-a159-ffd36a6b553b)

**Comment by mahrtayyab** [comment]
Yes it is a twitter server change and will be reflected after the next pypi release

**Comment by GoldOrange261** [comment]
I see, thanks for your reply!
