### ISSUE TITLE
Getting Unknown Error Occurs on Twitter when scraping using get_tweets with login

### ISSUE THREAD

**Issue by prog-mlml** [mahrtayyab/tweety#96]
In my scenario, I need to scrape every 2 seconds, and to get the latest tweets I need to log in. After a few seconds of execution I start to receive the error "Unknown Error Occurs on Twitter". Apparently this is a block for several close query attempts.
Is there any way to avoid this? Or some way to scrape to get the latest tweets without needing to log in?

Thanks

**Comment by dgw** [comment]
> Is there any way to avoid this?

Scrape slower or distribute the work across multiple clients/accounts.

> Or some way to scrape to get the latest tweets without needing to log in?

No.
