### ISSUE TITLE
SelfThread(tweets=2, all_tweets=2)

### ISSUE THREAD

**Issue by Madlife1** [mahrtayyab/tweety#97]
can't find all twitter 

"SelfThread(tweets=2, all_tweets=2)
SelfThread(tweets=3, all_tweets=3)
Tweet(id=1702685236184690903, author=User(id=1422537905885442055, username=CoinbaseAssets, name=Coinbase Assets 🛡️📞, verified=True), created_on=2023-09-15 14:06:09+00:00)
Tweet(id=1702002625720234199, author=User(id=1422537905885442055, username=CoinbaseAssets, name=Coinbase Assets 🛡️📞, verified=True), created_on=2023-09-13 16:53:42+00:00)
Tweet(id=1701989961921093905, author=User(id=1422537905885442055, username=CoinbaseAssets, name=Coinbase Assets 🛡️📞, verified=True), created_on=2023-09-13 16:03:23+00:00)
SelfThread(tweets=3, all_tweets=5)
SelfThread(tweets=2, all_tweets=2)
SelfThread(tweets=3, all_tweets=4)
Tweet(id=1699044118045859899, author=User(id=1422537905885442055, username=CoinbaseAssets, name=Coinbase Assets 🛡️📞, verified=True), created_on=2023-09-05 12:57:39+00:00)

  "

    from tweety import Twitter

    app = Twitter("session")
    app.load_auth_token("XXXXXXXXXXX")
    all_tweets = app.get_tweets("CoinbaseAssets")
    for tweet in all_tweets:

            print(tweet)

**Comment by Madlife1** [comment]
how to print the tweets in  SelfThread

**Comment by mahrtayyab** [comment]
More about [SelfThreads](https://mahrtayyab.github.io/tweety_docs/basic/twDataTypes.html#selfthread)

**Comment by Madlife1** [comment]
thankyou ！！！ good man ！！
