### ISSUE TITLE
tweety.exceptions_.UnknownError: [366] Invalid ATT for the flow

### ISSUE THREAD

**Issue by GunduzYuruyen** [mahrtayyab/tweety#99]
Hi, I using the code below I want to scrape related tweets with keyword, for each month.

For this I tried to use different username and password to handle Twitter blockade and I want to put into code a loop.

But ı take  "tweety.exceptions_.UnknownError: [366] Invalid ATT for the flow" error.

Can you help me?

**my code:**

client = tweety.Twitter("session")

Keyword = 'KEYWORD'
lang = 'lang:en'

clients = [
    ("USERNAME", " PASSWORD ", (datetime(2022, 1, 1), datetime(2022, 1, 31))),
    ("USERNAME2 ", " PASSWORD ", (datetime(2022, 2, 1), datetime(2022, 2, 28))),
    ("USERNAME3 ", " PASSWORD ", (datetime(2022, 3, 1), datetime(2022, 3, 31))),
    ("USERNAME4 ", " PASSWORD ", (datetime(2022, 4, 1), datetime(2022, 4, 30))),
    ("USERNAME5", " PASSWORD ", (datetime(2022, 5, 1), datetime(2022, 5, 31))),
    ("USERNAME6 ", " PASSWORD ", (datetime(2022, 6, 1), datetime(2022, 6, 30))),
    ("USERNAME7 ", " PASSWORD ", (datetime(2022, 7, 1), datetime(2022, 7, 31))),
    ("USERNAME8 ", " PASSWORD ", (datetime(2022, 8, 1), datetime(2022, 8, 31))),
    ("USERNAME9 ", " PASSWORD ", (datetime(2022, 9, 1), datetime(2022, 9, 30))),
    ("USERNAME10 ", " PASSWORD ", (datetime(2022, 10, 1), datetime(2022, 10, 31))),
    ("USERNAME11 ", " PASSWORD ", (datetime(2022, 11, 1), datetime(2022, 11, 30))),
    ("USERNAME12 ", "PASSWORD", (datetime(2022, 12, 1), datetime(2022, 12, 31)))
]

for username, password, (start_date, end_date) in clients:
    client.sign_in(username, password)

utc = pytz.UTC
tweets_data = []

while start_date <= end_date:
    end_date = start_date + timedelta(days=3)  # Get until date as start_date + 3 days
    start = f'since:{start_date.strftime("%Y-%m-%d")}'
    end = f'until:{end_date.strftime("%Y-%m-%d")}'

    search_query = f'{Keyword} {lang} {end} {start} -filter:links -filter:media'

    # Search for tweets
    for tweet in client.search(search_query, pages=5, wait_time=2):
        tweet_data = {
            'User': tweet.author.username,
            'User Name': tweet.author.name,
            'Tweet Text': tweet.text,
            'Tweet Creation Time': tweet.date.replace(tzinfo=utc).astimezone(pytz.timezone('UTC')).strftime('%Y-%m-%d %H:%M:%S')
            'Like Counts': tweet.likes,
            'Retweet Counts': tweet.retweet_counts,
            'View Counts': tweet.views
        }
        tweets_data.append(tweet_data)

   
    start_date = end_date + timedelta(days=1)

df = pd.DataFrame(tweets_data)

**Comment by Madlife1** [comment]
same question, i think the user and password never be  changed

**Comment by GunduzYuruyen** [comment]
> same question, i think the user and password never be changed

but otherwise it is not possible that multiple scraping

**Comment by mahrtayyab** [comment]
When you call `sign_in` again , you already have a` authenticated cookies` in the `request` , which caused it to fail , you can try create the list of clients saving them and then using it. But as far as I know , `cursor can't be shared between users`

**Comment by GunduzYuruyen** [comment]
thank you for your reply.
can you share with me an alternatve way to which can do my requiretments which i shared in my first message?
